-- CLEANUP: Remove unused tables
DROP TABLE IF EXISTS artists;

-- SCHEMA UPDATE: Add columns to labels if they don't exist
ALTER TABLE labels ADD COLUMN IF NOT EXISTS soundcloud_url text;
ALTER TABLE labels ADD COLUMN IF NOT EXISTS email text;

-- IMPORT LABELS (from Excel)
-- This section will contain the label import logic
-- Note: We TRUNCATE the table to ensure a clean import and remove sample data.
TRUNCATE TABLE labels RESTART IDENTITY CASCADE;

-- Insert Data (Labels Only)

INSERT INTO labels (name, subgenres, email, soundcloud_url, accepts_demos) VALUES
('Spinnin'' Main', ARRAY['Big Room','Electro House','Future House','Bass House','Dance','Psy-trance','Hard Dance|Hardcore'], 'jorn.heringa@spinninrecords.nl', 'https://soundcloud.com/spinninrecords', true),
('Spinnin''', ARRAY['Big Room','Electro House','Future House','Bass House','Dance','Psy-trance','Hard Dance|Hardcore'], 'marco@spinninrecords.nl', NULL, true),
('Revealed', ARRAY['Big Room','Hard Dance|Hardcore'], 'https://www.revealedrecordings.com/demo', 'https://soundcloud.com/revealed-recordings', true),
('Musical Freedom', ARRAY['Big Room','Electro House','Future House','House','Bass House','Dance'], 'demos@musicalfreedom.com', 'https://soundcloud.com/musical-freedom', true),
('Protocol', ARRAY['Big Room','Electro House'], 'https://protocolrecordings.com/demo/', 'https://soundcloud.com/protocolrecordings', true),
('Rave Culture', ARRAY['Big Room','Hard Dance|Hardcore'], 'demos@raveculture.com', 'https://soundcloud.com/raveculturemusic', true),
('Smash The House', ARRAY['Big Room','Electro House','Future House','Dance','Psy-trance','Hard Dance|Hardcore'], 'demo@smashthehouse.com', 'https://soundcloud.com/smashthehouse', true),
('Ultra Music', ARRAY['Big Room','Dubstep','Electro House','Future House','House','Melodic House & Techno','Progressive House','Minimal|Deep Tech','Tech House','Techno','Bass House','Dance','Psy-trance','Hard Dance|Hardcore'], 'demo@ultramusic.com', 'https://soundcloud.com/ultrarecords', true),
('Armada Music', ARRAY['Big Room','Electro House','Future House','Trance','Bass House','Dance','Psy-trance','Hard Dance|Hardcore'], 'https://demodrop.armadamusic.com/', 'https://soundcloud.com/armadamusic', true),
('Dharma Worldwide', ARRAY['Big Room','Electro House','Future House','Dance','Hard Dance|Hardcore'], 'submissions@dharma-worldwide.com', 'https://soundcloud.com/dharmaworldwide', true),
('Wall Recordings', ARRAY['Big Room','Electro House','Bass House'], 'https://wallrecordings.com/demodrop/  info@wallrecordings.com', 'https://soundcloud.com/wall-recordings', true),
('Guareber Recordings', ARRAY['Big Room'], 'guareberrecordingslabel@gmail.com', 'https://soundcloud.com/guareber-recordings', true),
('PinkStar Records', ARRAY['Big Room','Future House'], 'promo@sirupmusic.com', 'https://soundcloud.com/pinkstarrec', true),
('CYB3RPVNK', ARRAY['Big Room','Future House','Bass House','Dance','Psy-trance','Hard Dance|Hardcore'], 'https://goo.gl/PBBtBw', 'https://soundcloud.com/r3hab', true),
('STMPD RCRDS', ARRAY['Big Room','Electro House','Future House','Bass House','Dance'], 'demos@stmpdrcrds.com / steven@stmpdrcrds.com', 'https://soundcloud.com/stmpdrcrds', true),
('OZ Records', ARRAY['Big Room'], 'demo@oz-records.com', 'https://soundcloud.com/ozrecords', true),
('Fonk Recordings', ARRAY['Big Room','Electro House'], 'demo@fonkrecordings.com / fonkrecordings@gmail.com', 'https://soundcloud.com/fonkrecordings', true),
('Queen House Music', ARRAY['Big Room'], 'queenhousemusic@gmail.com', 'https://soundcloud.com/queenhousemusic', true),
('In My Opinion', ARRAY['Big Room'], 'demos@orjannilsen.com', NULL, true),
('Mixmash Records', ARRAY['Big Room','Future House','Dance'], 'demo.mixmashrecords.com', 'https://soundcloud.com/mixmash-records', true),
('Enhanced Music', ARRAY['Big Room','Future House','Trance','Dance'], 'https://www.labelradar.com/labels/enhancedmusic/portal', 'https://soundcloud.com/enhanced', true),
('Peak Hour Music', ARRAY['Big Room','Electro House','Bass House'], 'http://peakhourmusic.label-engine.com/demos', 'https://soundcloud.com/peak-hour-music-official', true),
('Harmor Records', ARRAY['Big Room'], 'demo@HarmorRecords.com https://harmorrecords.com/demo/', 'https://soundcloud.com/harmorrecords', true),
('SKINK', ARRAY['Big Room','Dubstep','Electro House','Future House','Hard Dance|Hardcore'], 'https://skinkrecords.com/submit-demo/', 'https://soundcloud.com/skinkofficial', true),
('inHarmony Music', ARRAY['Big Room','Trance','Psy-trance'], 'http://inharmonymusic.co/main/', NULL, true),
('Disruptor Records', ARRAY['Big Room','Future House'], 'info@disruptorrecords.com', 'https://soundcloud.com/disruptorrecs', true),
('TurnItUp Muzik', ARRAY['Big Room','Electro House'], 'https://turnitupmuzik.com/demo   demo@turnitupmuzik.com', 'https://soundcloud.com/turnitup-muzik', true),
('Release Records', ARRAY['Big Room','Future House'], 'demos@releaserecords.net', 'https://soundcloud.com/releaserecords', true),
('Toolroom Records', ARRAY['Big Room','House','Progressive House','Tech House'], 'https://toolroomrecords.com/demos/', 'https://soundcloud.com/toolroomrecords', true),
('SONO MUSIC', ARRAY['Big Room','Electro House','Progressive House'], 'http://www.sonomusic.nl/', NULL, true),
('Size Records', ARRAY['Big Room'], 'listen@size.net', 'https://soundcloud.com/sizerecords', true),
('Digital Empire Records', ARRAY['Big Room','Electro House'], 'https://www.label-worx.com/demo/digital-empire-records', 'https://soundcloud.com/digital-empire-records', true),
('Digital Complex Records', ARRAY['Big Room'], 'https://www.label-worx.com/demo/digital-empire-records', 'https://soundcloud.com/digital-complex-records', true),
('Ophelia Records', ARRAY['Big Room','Dubstep','Trance','Psy-trance'], 'demos@opheliarecords.com', 'https://soundcloud.com/ophelia_records', true),
('Reaching Altitude Records', ARRAY['Big Room','Trance'], 'demos@reachingaltitude.com', 'https://soundcloud.com/reachingaltituderecords', true),
('Darklight', ARRAY['Big Room','Electro House','Future House','Bass House','Dance'], 'http://www.darklightrecordings.com/site/demos/   demo@darklightrecordings.com', 'https://soundcloud.com/darklightrec', true),
('Hysteria', ARRAY['Big Room','Electro House','Future House','Bass House'], 'https://www.hysteriarecs.com/en/demo/     demos@hysteriarecs.com', 'https://soundcloud.com/hysteriarecords', true),
('Axtone', ARRAY['Big Room','Electro House','Future House','House','Bass House','Dance','Drum&Bass'], 'https://www.label-worx.com/demo/axtone', 'https://soundcloud.com/axtonemusic', true),
('Nando Records', ARRAY['Big Room','Electro House'], 'demo@nandorecords.com', 'https://soundcloud.com/nandorecords', true),
('So Much Dada', ARRAY['Big Room','Future House'], 'http://www.somuchdada.com/demo-submissions/', 'https://soundcloud.com/somuchdada', true),
('Piv Records', ARRAY['Deep House'], 'chris@pivrecords.com', 'https://soundcloud.com/pivrecords/', true),
('All Day I Dream', ARRAY['Deep House','Melodic House & Techno','Progressive House'], 'music@alldayidream.com', 'https://soundcloud.com/alldayidream', true),
('Crosstown Rebels', ARRAY['Deep House','House','Melodic House & Techno','Minimal|Deep Tech','Tech House','Afro House'], 'info@crosstownrebels.com', 'https://soundcloud.com/crosstownrebels', true),
('RADIANT.', ARRAY['Deep House','Melodic House & Techno','Afro House'], 'contact@radiantmusic.net', 'https://soundcloud.com/radiantmusicgroup', true),
('Pampa Records', ARRAY['Deep House','Electronica|Downtempo','House','Melodic House & Techno'], 'contact@pamparecords.com', 'https://soundcloud.com/pamparecords', true),
('Large Music', ARRAY['Deep House'], 'info@largemusic.com', 'https://soundcloud.com/large-music', true),
('Oh! Records Stockholm', ARRAY['Deep House'], 'ohstockholm@gmail.com', 'https://soundcloud.com/oh-records-stockholm', true),
('Hoomidaas Records', ARRAY['Deep House','Electronica|Downtempo'], 'demo@hoomidaas.com', 'https://soundcloud.com/hoomidaas', true),
('Ninja Tune', ARRAY['Deep House','Dubstep','Electronica|Downtempo'], 'demos@ninjatune.net', 'https://soundcloud.com/ninja-tune', true),
('Do Not Sit', ARRAY['Deep House','Afro House'], 'behrouzpromo@gmail.com', 'https://soundcloud.com/donotsit', true),
('MONOSIDE', ARRAY['Deep House'], 'demos@moodfunkrecords.com', 'https://soundcloud.com/monoside', true),
('Bar 25 Music', ARRAY['Deep House','Electronica|Downtempo','Afro House'], 'office@bar25.de', 'https://soundcloud.com/bar25', true),
('Exploited', ARRAY['Deep House','Afro House'], 'Send demos to our Soundcloud Dropbox', 'https://soundcloud.com/exploited', true),
('Anjunadeep', ARRAY['Deep House','Melodic House & Techno','Progressive House'], 'https://www.labelradar.com/labels/anjunabeats/portal', 'https://soundcloud.com/anjunadeep/', true),
('Gruuv', ARRAY['Deep House','Minimal|Deep Tech'], 'demos@gruuv.net', 'https://soundcloud.com/gruuv', true),
('DIRTYBIRD', ARRAY['Deep House','Tech House','Bass House','Breaks'], 'https://www.label-worx.com/demo/dirtybird', 'https://soundcloud.com/dirtybirdrecords', true),
('Bondage-Music', ARRAY['Deep House','Minimal|Deep Tech'], 'demo@bondage-music.com', 'https://soundcloud.com/bondage-music', true),
('Poker Flat Recordings', ARRAY['Deep House','Minimal|Deep Tech'], 'info@pokerflat-recordings.com', 'https://soundcloud.com/pokerflatrecordings', true),
('Kindisch', ARRAY['Deep House','Electronica|Downtempo'], 'https://proshare.audio/kindisch', 'https://soundcloud.com/kindisch', true),
('Songspire Records', ARRAY['Deep House','Progressive House'], 'onno@songspirerecords.com', 'https://soundcloud.com/songspirerecords', true),
('Highway Records', ARRAY['Deep House'], 'highway.official@gmail.com.', 'https://soundcloud.com/highwayrecords', true),
('FUSE London', ARRAY['Deep House','Minimal|Deep Tech','Tech House'], 'promo@fuselondon.net', 'https://soundcloud.com/fuselondon', true),
('Toy Tonics', ARRAY['Deep House'], 'info@toytonics.de', 'https://soundcloud.com/toytonics', true),
('Inermu', ARRAY['Deep House','Minimal|Deep Tech'], 'demos@inermu.com', 'https://soundcloud.com/inermu', true),
('PETS Recordings', ARRAY['Deep House','Tech House'], 'https://www.pets-recordings.com/contact', 'https://soundcloud.com/pets_recordings', true),
('Moon Harbour', ARRAY['Deep House','Tech House','Afro House'], 'demo@moonharbour.com', 'https://soundcloud.com/moon-harbour/', true),
('Power Plant Records', ARRAY['Deep House'], 'demo@power-plant.se', 'https://soundcloud.com/powerplantrecords', true),
('Madhouse Records', ARRAY['Deep House'], 'demos@madhouserecordsinc.com', 'https://soundcloud.com/madhouse-records', true),
('Ondulé Recordings', ARRAY['Deep House'], 'contact@ondulerecordings.com', 'https://soundcloud.com/ondulerecordings', true),
('Truesounds Music', ARRAY['Deep House','Melodic House & Techno'], 'demo@trsnds.com', 'https://soundcloud.com/truesounds-music-records', true),
('Transpecta', ARRAY['Deep House'], 'demo@transpecta.com', 'https://soundcloud.com/transpecta', true),
('Knee Deep In Sound', ARRAY['Deep House','House','Melodic House & Techno','Tech House'], 'demos@hotsince82.com', 'https://soundcloud.com/kneedeepinsound', true),
('Ready Mix Records', ARRAY['Deep House','Electronica|Downtempo'], 'http://www.label-worx.com/demo/ready-mix-records', 'https://soundcloud.com/ready-mix-records', true),
('EnormousTunes', ARRAY['Deep House','Future House','Melodic House & Techno'], 'demo.etr@gmail.com', 'https://soundcloud.com/enormoustunes', true),
('Maeve', ARRAY['Deep House'], 'maeverecords@gmail.com', 'https://soundcloud.com/maeverecords', true),
('Where The Heart Is', ARRAY['Deep House'], 'wheretheheartisny@gmail.com', 'https://soundcloud.com/wheretheheartis', true),
('Future Disco', ARRAY['Deep House'], 'info@futuredisco.net', 'https://soundcloud.com/future-disco', true),
('Induction Muzic', ARRAY['Deep House'], 'inductionmuzic@gmail.com', 'https://soundcloud.com/inductionmuzic', true),
('Salted Music', ARRAY['Deep House','House'], 'contact@saltedmusic.com', 'https://soundcloud.com/saltedmusic', true),
('Déepalma Records', ARRAY['Deep House','Afro House'], 'https://www.label-worx.com/demo/deepalma', 'https://soundcloud.com/deepalmarecords', true),
('DFTD', ARRAY['Deep House','House','Melodic House & Techno','Tech House'], 'demos@defected.com', 'https://soundcloud.com/dftd', true),
('Glitterboxibiza', ARRAY['Deep House','House'], 'demos@defected.com', 'https://soundcloud.com/glitterboxibiza', true),
('Deeperfect Records', ARRAY['Deep House','Minimal|Deep Tech'], 'info@deeperfect.com', 'https://soundcloud.com/deeperfect-records', true),
('Maya Recordings', ARRAY['Deep House','House','Tech House'], 'mayarecordings@gmail.com', 'https://soundcloud.com/mayarecordings', true),
('Glasgow Underground', ARRAY['Deep House','House','Tech House'], 'music@glasgowunderground.com', 'https://soundcloud.com/glasgowunderground', true),
('Akbal Music', ARRAY['Deep House','Afro House'], 'info@akbalmusic.com', 'https://soundcloud.com/akbalmusic', true),
('URSL', ARRAY['Deep House','Electronica|Downtempo'], 'demo@ursl-records.com', 'https://soundcloud.com/ursl', true),
('Too Many Rules', ARRAY['Deep House','House'], 'demos@toomanyrules.com', 'https://soundcloud.com/toomanyrulesmusic', true),
('fryhide', ARRAY['Deep House','Melodic House & Techno'], 'http://www.fryhide.com/demo/', 'https://soundcloud.com/fryhide', true),
('Embassy-One', ARRAY['Deep House','Melodic House & Techno'], 'info@embassyofmusic.de', 'https://soundcloud.com/embassy-one', true),
('Disciple', ARRAY['Dubstep','Psy-trance'], 'demos@disciplerecs.com', 'https://soundcloud.com/disciple', true),
('Disciple Round Table', ARRAY['Dubstep','Electro House'], 'demos@disciplerecs.com', 'https://soundcloud.com/discipleroundtable', true),
('Monstercat', ARRAY['Dubstep','Electro House','Bass House','Drum&Bass','Psy-trance','Hard Dance|Hardcore'], 'https://www.labelradar.com/labels/monstercat/portal', 'https://soundcloud.com/monstercat', true),
('Deadbeats', ARRAY['Dubstep','Bass House','Breaks','Drum&Bass'], 'https://docs.google.com/forms/d/e/1FAIpQLScr_NcnaHy7UB8RHaNYCaF8Ih-JJg6YU0bjGUtkmKsNgMu3hg/viewform?c=0&w=1', 'https://soundcloud.com/deadbeatsrecords', true),
('Bassrush', ARRAY['Dubstep','Drum&Bass'], 'Demos@Bassrush.com', 'https://soundcloud.com/bassrush', true),
('Dim Mak', ARRAY['Dubstep','Electro House','Future House','Bass House'], 'demos@dimmak.com', 'https://soundcloud.com/dimmakrecords', true),
('KANNIBALEN RECORDS', ARRAY['Dubstep','Electro House'], 'promo@kannibalenrecords.com', 'https://soundcloud.com/kannibalenrecords', true),
('Welcome Records', ARRAY['Dubstep','Hard Dance|Hardcore'], 'demos@welcomerecords.com', 'https://soundcloud.com/welcome-recs', true),
('Circus Records Official', ARRAY['Dubstep'], 'info@circus-records.co.uk', 'https://soundcloud.com/circusrecords', true),
('Wakaan', ARRAY['Dubstep'], 'Chloe@wakaan.com', 'https://soundcloud.com/wakaan', true),
('SubCarbon Records', ARRAY['Dubstep'], 'submissions@subcarbon.be', 'https://soundcloud.com/subcarbon', true),
('Mad Decent', ARRAY['Dubstep','Electro House','Future House','Bass House','Breaks','Dance'], 'https://maddecent.com/contact-us/', 'https://soundcloud.com/maddecent', true),
('Subtronics', ARRAY['Dubstep'], 'subtronicsofficial@gmail.com', 'https://soundcloud.com/subtronics', true),
('Emalkay', ARRAY['Dubstep'], 'beatsforemalkay@gmail.com', 'https://soundcloud.com/emalkay', true),
('JOYTIME COLLECTIVE', ARRAY['Dubstep','Bass House'], 'joytimecollective@gmail.com', 'https://soundcloud.com/joytimecollective', true),
('GAWDMODE', ARRAY['Dubstep'], 'mail@gawdmoderecords.com', 'https://soundcloud.com/gawdmoderecords', true),
('Seeking Blue', ARRAY['Dubstep'], 'Licensing@mrsuicidesheep.com', 'https://soundcloud.com/seeking-blue', true),
('UPLINK AUDIO', ARRAY['Dubstep'], 'uplinkaudiopromo@gmail.com', 'https://soundcloud.com/uplinkaudio', true),
('Firepower Records', ARRAY['Dubstep'], 'firepowerrecords@gmail.com', 'https://soundcloud.com/firepowerrecs', true),
('Savage Society Records', ARRAY['Dubstep'], 'savagesocietyofficial@gmail.com', 'https://soundcloud.com/savagesocietyrecords', true),
('Anjunabeats', ARRAY['Dubstep','Progressive House','Trance','Breaks'], 'https://www.labelradar.com/labels/anjunabeats/portal', 'https://soundcloud.com/anjunabeats', true),
('Buygore', ARRAY['Dubstep'], 'demo@buygore.com', 'https://soundcloud.com/buygore', true),
('40oz Cult', ARRAY['Dubstep'], '40ozCult@gmail.com', 'https://soundcloud.com/40ozcult', true),
('Bite This!', ARRAY['Dubstep','Bass House'], 'promo@heybitethis.com', 'https://soundcloud.com/heybitethis', true),
('F Audio', ARRAY['Dubstep'], 'http://labelfaudio.label-engine.com/demos', 'https://soundcloud.com/faudiodubs', true),
('Ōdio Records', ARRAY['Dubstep'], 'cedric@odiorecs.com', 'https://soundcloud.com/odiorecs', true),
('RAW AUDIO DISTORTION', ARRAY['Dubstep'], 'rawaudiodistortion@gmail.com', 'https://soundcloud.com/rawaudiodistortion', true),
('Rushdown', ARRAY['Dubstep'], 'https://www.labelradar.com/labels/rushdown/portal', 'https://soundcloud.com/rushdownrecs', true),
('Obskure Collective', ARRAY['Dubstep'], 'https://docs.google.com/forms/d/e/1FAIpQLSeoIHeEltcpiNtssO2p4sQ5QP7p_lqR5dtdjbgq2IjVJNXbeA/viewform', 'https://soundcloud.com/obskurecollective', true),
('Impossible Records', ARRAY['Dubstep'], 'submissions@impossiblerecs.com', 'https://soundcloud.com/impossible-records', true),
('CHATEAU BRUYANT', ARRAY['Dubstep'], 'chateaubruyant@gmail.com', 'https://soundcloud.com/chateau-bruyant', true),
('Phunk Junk Records', ARRAY['Dubstep','Bass House'], 'https://www.phunkjunk.com/demo-submission', 'https://soundcloud.com/phunkjunkrecordsinc', true),
('MMXVAC', ARRAY['Dubstep'], 'https://www.mmxvac.com/new-page', 'https://soundcloud.com/mmxvmusic', true),
('Play Me Records', ARRAY['Dubstep'], 'playmedubdrop@gmail.com', 'https://soundcloud.com/playmerecords', true),
('Gravitas Recordings', ARRAY['Dubstep'], 'http://gravitasrecordings.com/demo-submissions/', 'https://soundcloud.com/gravitas-recordings', true),
('RAM Records', ARRAY['Dubstep','Drum&Bass'], 'info@ramrecords.com', 'https://soundcloud.com/ramrecords', true),
('MONSTERS / MONSTERS MUSIC', ARRAY['Dubstep'], 'monstersdubstep@gmail.com', 'https://soundcloud.com/monstersdub', true),
('MA Music', ARRAY['Dubstep'], 'https://www.labelradar.com/labels/mostaddictive/portal', 'https://soundcloud.com/mostaddictivemusic', true),
('DemSixRecs', ARRAY['Dubstep'], 'DemienSixx@live.com', 'https://soundcloud.com/demiensixx', true),
('DramaClubRecs', ARRAY['Dubstep'], 'dramaclubrecordings@gmail.com', 'https://soundcloud.com/dramaclubrecs', true),
('Deep, Dark & Dangerous', ARRAY['Dubstep'], 'deepdarkdanger@gmail.com', 'https://soundcloud.com/deepdarkdangerous', true),
('Full Flex Audio', ARRAY['Dubstep'], 'https://www.label-worx.com/demo/full-flex-audio contact@fullflexaudio.co.uk', 'https://soundcloud.com/fullflexaudio', true),
('Insomniacrecs', ARRAY['Dubstep','House'], 'https://www.insomniacmusicgroup.com/label/insomniac-records/', 'https://soundcloud.com/insomniacrecords', true),
('OWSLA', ARRAY['Dubstep','Electro House','Future House','Bass House','Breaks','Dance','Hard Dance|Hardcore'], 'DEMOS@OWSLA.COM', 'https://soundcloud.com/owslaofficial', true),
('MULTIKILL RECORDINGS', ARRAY['Dubstep','Breaks'], 'multikillrecordings@gmail.com', 'https://soundcloud.com/multikillrecordings', true),
('Next Level Dubstep', ARRAY['Dubstep'], 'info@nextleveldubstep.com', 'https://soundcloud.com/nextleveldubs', true),
('HEAVY ARTILLERY RECORDINGS', ARRAY['Dubstep'], 'info@heavyartilleryrecordings.com', 'https://soundcloud.com/faustandshortee', true),
('Spinnin'' Records Talent Pool', ARRAY['Electro House','Future House','Bass House','Dance','Psy-trance','Hard Dance|Hardcore'], 'https://spinninrecords.com/talentpool/', 'https://soundcloud.com/spinninrecords-talentpool', true),
('Spinnin'' Copyright Free', ARRAY['Electro House','Future House','Bass House','Dance','Psy-trance','Hard Dance|Hardcore'], 'marrit@spinninrecords.nl', 'https://soundcloud.com/spinnincopyrightfreemusic', true),
('Playbox', ARRAY['Electro House'], 'demo@playbox-music.com', 'https://soundcloud.com/itsplayboxmusic', true),
('Heldeep', ARRAY['Electro House','Future House','House','Bass House','Dance'], 'https://oliverheldens.com/demo-drop/   oliverheldens@gmail.com', 'https://soundcloud.com/HeldeepRecords', true),
('Mixmash / Ones To Watch', ARRAY['Electro House','Bass House'], 'http://www.mixmashrecords.com/demo-drop', 'https://soundcloud.com/mixmash-records', true),
('S2 Records', ARRAY['Electro House'], 'promo@sirupmusic.com', 'https://soundcloud.com/sirupmusic', true),
('Moon Records', ARRAY['Electro House'], 'moonrecordsceo@gmail.com', 'https://soundcloud.com/moonrecords', true),
('Hexagon / Generation Hex', ARRAY['Electro House','Future House'], 'https://www.hexagonhq.com/demos/', 'https://soundcloud.com/hexagon', true),
('Bourne Recordings', ARRAY['Electro House'], 'http://labelbournerecordings.label-engine.com/demos', 'https://soundcloud.com/bourne-recordings', true),
('S I Z E', ARRAY['Electro House'], 'listen@size.net', 'https://soundcloud.com/sizerecords', true),
('Brooklyn Fire', ARRAY['Electro House'], 'demos@brooklynfirerecords.com', 'https://soundcloud.com/brooklynfire', true),
('FRKNTN', ARRAY['Electro House'], 'demo@frkntn.com', 'https://soundcloud.com/wearefrkntn', true),
('PREMIERE CLASSE', ARRAY['Electro House'], 'demos@premiereclasserecords.com', NULL, true),
('Confession', ARRAY['Electro House','Future House','Bass House'], 'confessionlabel@gmail.com', 'https://soundcloud.com/confession', true),
('Dirty Dutch', ARRAY['Electro House','Bass House'], 'https://bit.ly/DDM_DEMO', 'https://soundcloud.com/dirtydutchmusic', true),
('Hungry Koala Records', ARRAY['Electro House'], 'http://hungrykoalarecords.label-engine.com/demos', 'https://soundcloud.com/hungrykoalarecords', true),
('Punks Music', ARRAY['Electro House','Bass House','Breaks'], 'info@punksmusic.com', 'https://soundcloud.com/punksmusic', true),
('Big Fish Recordings', ARRAY['Electro House'], 'demos@bigfishrecordings.com', 'https://soundcloud.com/big-fish-recordings', true),
('Lowded Recordings', ARRAY['Electro House','Bass House','Hard Dance|Hardcore'], 'http://lowdedrecordings.label-engine.com/demos', 'https://soundcloud.com/lowdedrecordings', true),
('Lime Records', ARRAY['Electro House'], 'http://labellimerecords.label-engine.com/demos', 'https://soundcloud.com/korealimerecords', true),
('AUSTRO MUSIC', ARRAY['Electro House'], 'contato@austromusic.com.br', NULL, true),
('Found Frequencies', ARRAY['Electro House','Future House','Dance'], 'demo@foundfrequencies.com', 'https://soundcloud.com/user-856466205', true),
('.CULTR records', ARRAY['Electro House'], 'demo@cultr-records.com', 'https://soundcloud.com/cultrrecords', true),
('The Power House', ARRAY['Electro House'], 'demo@thepowerhouse.io', 'https://soundcloud.com/thepowerhouse', true),
('We Are Diamond', ARRAY['Electro House','Future House'], 'https://wearediamond.net/demo-submission/', 'https://soundcloud.com/wearediamond', true),
('Bromuda Records', ARRAY['Electro House'], 'bromudarecords@gmail.com', 'https://soundcloud.com/bromudarecords', true),
('DOPE SQVAD', ARRAY['Electro House'], 'demo@dopesqvad.com', 'https://soundcloud.com/dopesqvad', true),
('Cinematik Recordings', ARRAY['Electro House','Hard Dance|Hardcore'], 'Cinematikrecordings@outlook.com', 'https://soundcloud.com/cinematikrecordings?fbclid=IwAR26t6LpXbHo9Iy7U7MSrFNRScB2eXVEEjBqc08-RUWElwb4xsKnj01Lj-s', true),
('Metanoia Music', ARRAY['Electro House'], 'https://metanoiamusic.demodrop.com/', 'https://soundcloud.com/metanoiam', true),
('In my Opinion (Armada Music)', ARRAY['Electro House','Trance'], 'demos@orjannilsen.com,', 'https://soundcloud.com/armadamusic', true),
('Plasma.digital', ARRAY['Electro House'], 'http://plasmapool.com/contact/demo/', 'https://soundcloud.com/plasma-digital', true),
('Uprise Music', ARRAY['Electro House','Bass House'], 'info@uprisemusic.com', 'https://soundcloud.com/uprisemusicofficial', true),
('FVYDID', ARRAY['Electro House'], NULL, 'https://soundcloud.com/fvydid', true),
('Pipe & Pochet', ARRAY['Electronica|Downtempo','Afro House'], 'info@pipeandpochet.com', 'https://soundcloud.com/pipeandpochet', true),
('Stil vor Talent', ARRAY['Electronica|Downtempo','Melodic House & Techno','Progressive House','Techno','Afro House'], 'demo@stilvortalent.de', 'https://soundcloud.com/stilvortalent', true),
('SHANGO RECORDS', ARRAY['Electronica|Downtempo'], 'shangorecordings@gmail.com', 'https://soundcloud.com/shango-records', true),
('Kamai Music', ARRAY['Electronica|Downtempo','Afro House'], 'demos@kamaimusic.com', 'https://soundcloud.com/kamaimusic', true),
('Underyourskin Records', ARRAY['Electronica|Downtempo'], 'alex@uysr.de', 'https://soundcloud.com/underyourskinrecords', true),
('Hungry Music', ARRAY['Electronica|Downtempo'], 'licensing@hungrymusic.fr', 'https://soundcloud.com/hungry-music', true),
('!K7 Records', ARRAY['Electronica|Downtempo'], 'http://www.k7.com/', 'https://soundcloud.com/k7-records', true),
('LNDKHN', ARRAY['Electronica|Downtempo'], 'contact@lndkhn.com', 'https://soundcloud.com/lndkhn', true),
('Souq Records', ARRAY['Electronica|Downtempo'], 'Aser@Souqrecords.net', 'https://soundcloud.com/souqrecordss', true),
('Rebellion der Träumer', ARRAY['Electronica|Downtempo'], 'Label@rebellion-der-traeumer.com', 'https://soundcloud.com/rebelliondertraumer', true),
('Serafin Audio Imprint', ARRAY['Electronica|Downtempo'], 'info@serafinaudio.com', 'https://soundcloud.com/serafinaudio', true),
('Ouïe', ARRAY['Electronica|Downtempo'], 'contact@ouiemusic.com', 'https://soundcloud.com/ouiemusic', true),
('Keinemusik', ARRAY['Electronica|Downtempo','Melodic House & Techno','Afro House'], 'drop@keinemusik.com', 'https://soundcloud.com/keinemusik', true),
('Fabric', ARRAY['Electronica|Downtempo','Dance'], 'info@fabriclondon.com', 'https://soundcloud.com/fabric', true),
('AKUMANDRA', ARRAY['Electronica|Downtempo'], 'info@akumandra.com', 'https://soundcloud.com/akumandra', true),
('Earthly Delights', ARRAY['Electronica|Downtempo'], 'EarthlyDelightsMusic@gmail.com', 'https://soundcloud.com/delightsearthly', true),
('Flying Circus', ARRAY['Electronica|Downtempo','Melodic House & Techno'], 'demos@audioflymusic.com', 'https://soundcloud.com/we-are-flying-circus', true),
('NCTRNL', ARRAY['Electronica|Downtempo'], 'mail@nctrnlrecords.com', 'https://soundcloud.com/nctrnlrecords', true),
('Lump Records', ARRAY['Electronica|Downtempo'], 'lump.rec.demos@gmail.com', 'https://soundcloud.com/lump-rec', true),
('Amselcom', ARRAY['Electronica|Downtempo'], 'https://amselcom.de/contact/', 'https://soundcloud.com/amselcom', true),
('Circles & Stones', ARRAY['Electronica|Downtempo'], 'demo@circles-and-stones.com', 'https://soundcloud.com/circlesandstones', true),
('Bercana Music', ARRAY['Electronica|Downtempo'], 'demos@bercanamusic.com', 'https://soundcloud.com/bercana', true),
('3000Grad / Acker Records', ARRAY['Electronica|Downtempo'], 'OFFICE@3000GRAD.COM', 'https://soundcloud.com/3000-grad', true),
('ART VIBES', ARRAY['Electronica|Downtempo'], 'studio@artvibesmusic.com', 'https://soundcloud.com/art-vibes-music', true),
('MŎNɅDɅ', ARRAY['Electronica|Downtempo'], 'monada.musica@gmail.com', 'https://soundcloud.com/monada-project', true),
('Moodfamily', ARRAY['Electronica|Downtempo'], 'gilles@moodfamily.net', 'https://soundcloud.com/moodfamily', true),
('Heimlich Musik', ARRAY['Electronica|Downtempo'], 'hello@heimlich.online', 'https://soundcloud.com/heimlichaufsc', true),
('THE MAGIC MOVEMENT', ARRAY['Electronica|Downtempo'], 'info@themagicmovement.com', 'https://soundcloud.com/the-magic-movement', true),
('Leveldva', ARRAY['Electronica|Downtempo'], 'Leveldva.events@Gmail.com', 'https://soundcloud.com/leveldva-music', true),
('Degustibus Music', ARRAY['Electronica|Downtempo'], 'https://www.degustibusmusic.com/contact', 'https://soundcloud.com/degustibus-music', true),
('Tal der Verwirrung', ARRAY['Electronica|Downtempo'], 'struppie@talderverwirrung.de', 'https://soundcloud.com/talderverwirrung', true),
('Kompakt', ARRAY['Electronica|Downtempo','Melodic House & Techno','Techno'], 'label@kompakt.fm', 'https://soundcloud.com/kompakt', true),
('Harabe', ARRAY['Electronica|Downtempo'], 'demo@haraberecords.com', 'https://soundcloud.com/haraberecords', true),
('Balance Series', ARRAY['Electronica|Downtempo','Progressive House'], 'info@balancemusic.com.au', 'https://soundcloud.com/balance-series', true),
('Laut & Luise', ARRAY['Electronica|Downtempo'], 'hello(at)lautundlui.se', 'https://soundcloud.com/lautundluise', true),
('Diynamic Music', ARRAY['Electronica|Downtempo','Melodic House & Techno'], 'solomundemo@diynamic.com', 'https://soundcloud.com/diynamic-music', true),
('hfn music', ARRAY['Electronica|Downtempo'], 'humans@hfn-music.com', 'https://soundcloud.com/hfn-music', true),
('LIFE AND DEATH', ARRAY['Electronica|Downtempo'], 'velvetam@gmail.com', 'https://soundcloud.com/lifeanddeath', true),
('Exotic Refreshment', ARRAY['Electronica|Downtempo'], 'demo@exoticrefreshment.com', 'https://soundcloud.com/exotic-refreshment', true),
('TAU', ARRAY['Electronica|Downtempo','Melodic House & Techno','Afro House'], 'carsten@tautautau.de', 'https://soundcloud.com/tautautauofficial', true),
('permanent vacation', ARRAY['Electronica|Downtempo'], 'https://perm-vac.com/contact/', 'https://soundcloud.com/permvac', true),
('KYBELE', ARRAY['Electronica|Downtempo'], 'kybelean@gmail.com', 'https://soundcloud.com/kybelean', true),
('Ladino Romance', ARRAY['Electronica|Downtempo'], 'ladinoromance@gmail.com', 'https://soundcloud.com/ladinoromance', true),
('Armada Electronic Elements', ARRAY['Electronica|Downtempo','Melodic House & Techno'], 'https://www.label-worx.com/demo/armadamusic?fbclid=IwAR0zzBMM9cyRfpC5kptNvEBn-4GIV6hobXcQXxJb6GQuf5LJW-rLW6oHFmQ', 'https://soundcloud.com/electronicelements', true),
('Black Book Records', ARRAY['Future House','Tech House','Bass House'], 'https://docs.google.com/forms/d/e/1FAIpQLSchp_wvh3dgi37o4UkE5CO72K7Nl0R3ckxd5r-0RU2Xk98ZjQ/viewform', 'https://soundcloud.com/blackbookrecs', true),
('Equal Vision Records', ARRAY['Future House'], 'music@equalvision.com', 'https://soundcloud.com/equalvision', true),
('Future House Music', ARRAY['Future House'], 'https://futurehousemusic.net/demo-submission/', 'https://soundcloud.com/futurehousemusic', true),
('CLUB SWEAT', ARRAY['Future House','House','Tech House','Bass House'], 'https://sweatitoutmusic.com/contact/', 'https://soundcloud.com/sweat-it-out-music', true),
('Enormous Chills', ARRAY['Future House','Bass House'], 'demo.etr@gmail.com.', 'https://soundcloud.com/enormouschills', true),
('AFTR:HRS', ARRAY['Future House','Progressive House','Bass House','Dance'], 'demos@aftrhrsrecords.com', 'https://soundcloud.com/aftrhrsrecords', true),
('Night Bass', ARRAY['Future House','Bass House'], 'http://www.nightbassrecords.com/contact', 'https://soundcloud.com/nightbassrecords', true),
('DO NOT DUPLICATE RECORDINGS', ARRAY['Future House'], 'https://docs.google.com/forms/d/e/1FAIpQLSdG2LCX9xw-ERNGcCuikv_H5ZrmzVf3FA3R-h8TKncBWJld3w/viewform', 'https://soundcloud.com/dndrecs', true),
('Big & Dirty Records', ARRAY['Future House'], 'https://beyourselfmusic.com/legacy/demos/', 'https://soundcloud.com/biganddirtyrecords', true),
('Selected.', ARRAY['Future House'], 'inbox@selectedbase.com', 'https://soundcloud.com/selected-stream', true),
('Sirup Music', ARRAY['Future House'], 'https://www.submithub.com/submit?to=blogs', 'https://soundcloud.com/sirupmusic', true),
('Night Service Only', ARRAY['Future House','Bass House'], 'https://www.cidmusic.com/', 'https://soundcloud.com/nightserviceonly', true),
('Kosmo Music', ARRAY['Future House','Techno','Trance'], 'demo@kosmomusic.com', 'https://soundcloud.com/kosmomusic', true),
('PARAMETRIC', ARRAY['Future House','Dance'], 'promos@parametricrecords.com', 'https://soundcloud.com/parametricrecs', true),
('No Definition', ARRAY['Future House'], 'demo.etr@gmail.com', 'https://soundcloud.com/nodefinitionrecords', true),
('Protocol Recordings', ARRAY['Future House'], 'https://protocol-recordings.com/demo/', 'https://soundcloud.com/protocolrecordings', true),
('World Famous Headquarters', ARRAY['Future House','Bass House'], 'worldfamousheadquarters@gmail.com', 'https://soundcloud.com/world-famous-headquarters', true),
('SOLOTOKO', ARRAY['Future House','House','Tech House','Dance'], 'contact@solotoko.com', 'https://soundcloud.com/solotoko', true),
('Kontor Records', ARRAY['Future House','Hard Dance|Hardcore'], 'Robert.larsz@kontorrecords.de', 'https://soundcloud.com/kontor', true),
('This Ain''t Bristol', ARRAY['Future House','House','Tech House','Bass House'], 'demos@thisaintbristol.com', 'https://soundcloud.com/thisaintbristol', true),
('Rising Music', ARRAY['Future House'], 'demos@risingmusic.co.uk', 'https://soundcloud.com/risingmusic', true),
('Never Say Die Records', ARRAY['Future House'], 'https://wewillneversaydie.com/contact/', 'https://soundcloud.com/neversaydie', true),
('Thrive Music', ARRAY['Future House'], 'demos@thrivemusic.com', 'https://soundcloud.com/thrivemusic', true),
('Elevation', ARRAY['Future House','Bass House'], 'demos@elevationmusicrecords.com', 'https://soundcloud.com/elevationmusicrecords', true),
('HARD', ARRAY['Future House'], 'https://hardfest.com/contact-us/', 'https://soundcloud.com/hardfest', true),
('Which Bottle?', ARRAY['Future House','Dance'], 'http://eng.whichbottle.ru/page/demo.html', 'https://soundcloud.com/whichbottle', true),
('Vicious Recordings', ARRAY['Future House','House'], 'https://www.label-worx.com/demo/viciousdemobox', 'https://soundcloud.com/viciousrecordings', true),
('MAD ZOO', ARRAY['Future House'], 'madzoodemos@gmail.com', 'https://soundcloud.com/madzoomusic', true),
('BMKLTSCH RCRDS', ARRAY['Future House'], 'music@bmkltschrcrds.com', 'https://soundcloud.com/bmkltschrcrds', true),
('Defected Records', ARRAY['House','Tech House','Afro House','Dance'], 'demos@defected.com', 'https://soundcloud.com/defectedrecords', true),
('Downtown Underground', ARRAY['House'], 'downtownundergrounddemos@gmail.com', 'https://soundcloud.com/downtownundergroundmusic', true),
('Hot Creations', ARRAY['House','Tech House'], 'https://soundcloud.com/allhcdemos', 'https://soundcloud.com/hot-creations', true),
('Armada Subjekt', ARRAY['House','Bass House'], 'https://www.label-worx.com/demo/armadamusic?fbclid=IwAR29mpDlusDF_FhJjSu4iO8PpaztBYdtVrUsplX88IXXPJL0BEezFJAEu5Q', 'https://soundcloud.com/armada-subjekt', true),
('REKIDS', ARRAY['House','Techno'], 'loverekids@gmail.com', 'https://soundcloud.com/rekids', true),
('Cr2 Records', ARRAY['House','Tech House','Techno'], 'demos@cr2records.com', NULL, true),
('Running Back Records', ARRAY['House','Minimal|Deep Tech','Techno'], 'label@running-back.com', 'https://soundcloud.com/runningback', true),
('Snatch! Records', ARRAY['House','Tech House'], 'demos@snatchrecords.com', 'https://soundcloud.com/snatchrecords', true),
('Simma Black', ARRAY['House'], 'simmablack@gmail.com', 'https://soundcloud.com/simma-black', true),
('Mother-recordings', ARRAY['House'], 'https://soundcloud.com/mother-recordings', 'https://soundcloud.com/mother-recordings', true),
('Cuttin'' Headz', ARRAY['House'], 'demos@cuttinheadz.com', 'https://soundcloud.com/cuttinheadzmusic', true),
('TRICK', ARRAY['House','Tech House','Techno'], 'demos@tricklabel.co.uk', 'https://soundcloud.com/trick_label', true),
('ORIGINS RCRDS', ARRAY['House','Tech House'], 'originsrcrdsdemos@gmail.com', NULL, true),
('FOUR THIRTY TWO', ARRAY['House'], 'promos at fourthirty2 . Com', 'https://soundcloud.com/fourthirty2', true),
('Let There Be House Records', ARRAY['House'], 'demo@ltbh.co.uk', 'https://soundcloud.com/lettherebehouserecords', true),
('Milk & Sugar Recordings', ARRAY['House'], 'https://www.label-worx.com/demo/milkandsugarrec', 'https://soundcloud.com/milkandsugarrecordings', true),
('Armada Deep', ARRAY['House'], 'https://demodrop.armadamusic.com/', 'https://soundcloud.com/armada-deep', true),
('Phoenix Music', ARRAY['House'], 'demos@phoenixmusicinc.com', 'https://soundcloud.com/phoenixmusicinc', true),
('FFRR', ARRAY['House','Progressive House','Afro House','Dance'], 'demos@ffrrecords.com', 'https://soundcloud.com/ffrr-records', true),
('Subliminal Records', ARRAY['House'], 'tracks@subliminalrecords.com', 'https://soundcloud.com/subliminal-records', true),
('Strictly Rhythm', ARRAY['House','Breaks','Dance'], 'demos@strictly.com', 'https://soundcloud.com/strictlyrhythm', true),
('Transa Records', ARRAY['House','Afro House'], 'demotransarecords@gmail.com', 'https://soundcloud.com/transa_records', true),
('Zulurecords', ARRAY['House'], 'A&R@zulurecords.co.uk', 'https://soundcloud.com/zulurecords', true),
('KITTBALL', ARRAY['House','Minimal|Deep Tech','Tech House','Afro House'], 'https://www.kittball.com/#connect', 'https://soundcloud.com/kittball', true),
('Lapsus Music', ARRAY['House','Tech House'], 'http://www.lapsusmusic.com/demos?fbclid=IwAR1uBWGh7DvjHmZ2xxhzqRFK8Ny98wv9tFT7DHEY4QURrWo7zW6oFKV-ZW8', 'https://soundcloud.com/lapsus-music', true),
('Z Records', ARRAY['House'], 'gordon@zrecords.ltd.uk', 'https://soundcloud.com/thezrecords', true),
('Food Music', ARRAY['House'], 'demos@foodmusic.co.uk', 'https://soundcloud.com/foodmusicuk', true),
('Cécille Records', ARRAY['House','Minimal|Deep Tech','Tech House'], 'https://www.cecille-records.de/', 'https://soundcloud.com/cecille-records', true),
('Motive Records', ARRAY['House'], 'demos@motiverecords.com.au', 'https://soundcloud.com/motiverecordsau', true),
('Déepalma Soul', ARRAY['House'], 'https://www.label-worx.com/demo/deepalma', 'https://soundcloud.com/deepalmasoul', true),
('Solid Grooves Records', ARRAY['House','Minimal|Deep Tech','Tech House','Bass House'], 'demos@solidgrooves.co.uk', 'https://soundcloud.com/solidgrooves-records', true),
('CRUISE MUSIC', ARRAY['House'], 'cruisemusicme@gmail.com', 'https://soundcloud.com/cruisemusicme', true),
('Total Freedom Recordings', ARRAY['House'], 'totalfreedom@invidiarecords.com', 'https://soundcloud.com/totalfreedomrecordings', true),
('Urbana Recordings', ARRAY['House'], 'demos@urbanarecordings.com', 'https://soundcloud.com/urbanarecordings', true),
('Repopulate Mars', ARRAY['House','Tech House'], 'demos@repopulatemars.com', 'https://soundcloud.com/repopulatemars', true),
('La Luna Records', ARRAY['House','Tech House'], 'demo@lalunarecords.com', 'https://soundcloud.com/user-507559505', true),
('Guesthouse Music', ARRAY['House'], 'http://www.guesthousemusic.com/#tm-bottom-d', 'https://soundcloud.com/guesthousemusic', true),
('Shall Not Fade', ARRAY['House'], 'https://docs.google.com/forms/d/e/1FAIpQLScSvQ0UkMGwHLxxdxV8xOc0aFqr_qX1uNbxV_79vFntkertvw/viewform', 'https://soundcloud.com/shallnotfade', true),
('INKAL / META', ARRAY['House','Minimal|Deep Tech','Tech House'], 'demos@inkalmeta.com', 'https://soundcloud.com/inkal_meta', true),
('Purveyor Underground', ARRAY['House'], 'musicfirst@purveyorunderground.com', 'https://soundcloud.com/purveyorunderground', true),
('Savedrecords', ARRAY['House'], 'saveddemos@gmail.com', 'https://soundcloud.com/savedrecords', true),
('Freakin Music / The Home Of Freakin 909/303', ARRAY['House'], 'Freakindemo@gmx.co.uk', 'https://soundcloud.com/freakin909', true),
('Afterlife', ARRAY['Melodic House & Techno','Techno'], 'demo@after.life', 'https://soundcloud.com/afterlifeofc', true),
('Eleatics Records', ARRAY['Melodic House & Techno','Progressive House'], 'eleaticsdemo@gmail.com', 'https://soundcloud.com/eleatics', true),
('Blaufield Music', ARRAY['Melodic House & Techno'], 'contact@bookashade.com', 'https://soundcloud.com/blaufield-music', true),
('Last Night On Earth', ARRAY['Melodic House & Techno','Techno','Afro House'], 'maren@lnoearth.com', 'https://soundcloud.com/last-night-on-earth', true),
('Love Matters Music', ARRAY['Melodic House & Techno','Afro House'], 'demo@love-matters.de', 'https://soundcloud.com/lovemattersmusic', true),
('Renaissance Records', ARRAY['Melodic House & Techno','Techno'], 'music@renaissance.dj', 'https://soundcloud.com/renaissance-recordings', true),
('Ellum', ARRAY['Melodic House & Techno'], 'demos@ellumaudio.com', 'https://soundcloud.com/ellum', true),
('Selador Recordings', ARRAY['Melodic House & Techno','Progressive House','Afro House'], 'steve@seladorrecordings.com', 'https://soundcloud.com/selador-recordings', true),
('RUKUS', ARRAY['Melodic House & Techno','Techno'], 'demo@rukusofficial.com', 'https://soundcloud.com/rukusofficial', true),
('Yoshitoshi', ARRAY['Melodic House & Techno'], 'info@yoshitoshi.com', 'https://soundcloud.com/yoshitoshi', true),
('Drumcode', ARRAY['Melodic House & Techno','Techno'], 'demo@drumcode.se', 'https://soundcloud.com/drumcode', true),
('Siamese', ARRAY['Melodic House & Techno'], 'siamesedemos@gmail.com', 'https://soundcloud.com/siameserecords', true),
('Timeless Moment', ARRAY['Melodic House & Techno','Progressive House'], 'demos@timelessmoment.com.br', 'https://soundcloud.com/timelessmoment', true),
('Dear Deer Records', ARRAY['Melodic House & Techno','Progressive House'], 'http://deardeerrecords.com/demo/', 'https://soundcloud.com/deardeerrecords', true),
('Sapiens', ARRAY['Melodic House & Techno'], 'contact@sapiens.fm', 'https://soundcloud.com/sapiensrecords', true),
('Cocoon Recordings', ARRAY['Melodic House & Techno','Techno'], 'demo@cocoon.net', 'https://soundcloud.com/cocoonrecordings', true),
('Lost on You', ARRAY['Melodic House & Techno','Afro House'], 'demos@lostonyoumusic.com', 'https://soundcloud.com/lostonyoumusic', true),
('Discotexas', ARRAY['Melodic House & Techno'], 'demos@discotexas.com', 'https://soundcloud.com/discotexas', true),
('Tale + Tone', ARRAY['Melodic House & Techno'], 'demo@taleandtone.com', 'https://soundcloud.com/taleandtone', true),
('ZEHN Records', ARRAY['Melodic House & Techno','Afro House'], 'demo@zehn-records.com', 'https://soundcloud.com/zehnrecords', true),
('DAYS like NIGHTS', ARRAY['Melodic House & Techno'], 'https://www.label-worx.com/demo/days-like-nights', 'https://soundcloud.com/dayslikenightsofficial', true),
('Einmusika Recordings', ARRAY['Melodic House & Techno','Progressive House','Minimal|Deep Tech'], 'demo@einmusika.com', 'https://soundcloud.com/einmusika-recordings', true),
('STEYOYOKE', ARRAY['Melodic House & Techno'], 'https://www.steyoyoke.com/submit-your-demo/', 'https://soundcloud.com/steyoyoke', true),
('Different', ARRAY['Melodic House & Techno','Afro House'], 'differentdemos@pias.com', 'https://soundcloud.com/differentrecordings', true),
('Beatfreak Recordings', ARRAY['Melodic House & Techno','Progressive House'], 'demos@beatfreakgroup.com', 'https://soundcloud.com/beatfreak-recordings', true),
('REALM', ARRAY['Melodic House & Techno','Tech House'], 'realm@infectiouspr.com', 'https://soundcloud.com/realmrecords1', true),
('Parquet Recordings', ARRAY['Melodic House & Techno','Progressive House'], 'demos@parquet-recordings.com', 'https://soundcloud.com/parquetrecordings', true),
('Audiophile Deep', ARRAY['Melodic House & Techno'], 'https://www.apmg.io/submit-demo/', 'https://soundcloud.com/audiophiledeep', true),
('PHANTASY SOUND', ARRAY['Melodic House & Techno'], 'demos@phantasysound.co.uk', 'https://soundcloud.com/phantasysound', true),
('Vivrant', ARRAY['Melodic House & Techno'], 'demos@vivrant.nu', 'https://soundcloud.com/vivrantmusic', true),
('Tenampa Recordings', ARRAY['Melodic House & Techno'], 'demos@tenampa.mx', 'https://soundcloud.com/tenampa-recordings', true),
('Bodhi Collective', ARRAY['Melodic House & Techno'], 'https://www.apmg.io/submit-demo/', 'https://soundcloud.com/bodhicollective', true),
('JEAHMON! Records', ARRAY['Melodic House & Techno'], 'jeahmon@marc-depulse.com', 'https://soundcloud.com/jeahmon', true),
('Saisons', ARRAY['Melodic House & Techno'], 'https://saisonsmusique.com/demosubmission', 'https://soundcloud.com/saisonsmusique', true),
('Suara', ARRAY['Melodic House & Techno'], 'http://www.suara-music.com/contact/', 'https://soundcloud.com/suara', true),
('mobilee', ARRAY['Melodic House & Techno','Afro House'], 'demo@mobilee-records.de', 'https://soundcloud.com/mobilee-records', true),
('Filth on Acid', ARRAY['Melodic House & Techno','Techno'], 'demos@filthonacid.nl', 'https://soundcloud.com/filthonacid', true),
('monaberry', ARRAY['Melodic House & Techno'], 'demos@monaberry.de', 'https://soundcloud.com/monaberry', true),
('microcastle', ARRAY['Melodic House & Techno','Afro House'], 'http://www.microcastlemusic.com/contact', 'https://soundcloud.com/microcastle', true),
('Voyeur Music', ARRAY['Melodic House & Techno'], 'demos@voyeurmusic.co.uk', 'https://soundcloud.com/voyeurmusic', true),
('SINCOPAT', ARRAY['Melodic House & Techno','Progressive House'], 'demos@sincopat.com', 'https://soundcloud.com/sincopat', true),
('WEITER', ARRAY['Melodic House & Techno'], 'demo@olivierweiter.com', 'https://soundcloud.com/weitermusic', true),
('Outta Limits Recordings', ARRAY['Progressive House'], 'demos@outtalimitsrecordings.com', 'https://soundcloud.com/outta-limits-recordings', true),
('Lost & Found', ARRAY['Progressive House'], 'demos@lostandfoundrecordings.com', 'https://soundcloud.com/lostandfoundrec', true),
('FSOE UV', ARRAY['Progressive House'], 'uv@futuresoundofegypt.com', 'https://soundcloud.com/fsoeuv', true),
('Sudbeat Music', ARRAY['Progressive House'], 'demos@sudbeat.com', 'https://soundcloud.com/sudbeat', true),
('Replug Records', ARRAY['Progressive House'], 'demo@replugrecords.com', 'https://soundcloud.com/replug', true),
('Stereo Productions', ARRAY['Progressive House','Techno'], 'POCAS@STEREO-PRODUCTIONS.COM', 'https://soundcloud.com/stereoproductions', true),
('Beat Boutique Records', ARRAY['Progressive House'], 'beatboutiquerecords@gmail.com', 'https://soundcloud.com/beat-boutique-rec', true),
('Freegrant Music / Big Toys Prod.', ARRAY['Progressive House'], 'https://www.label-worx.com/demo/freegrant-music', 'https://soundcloud.com/fg-music', true),
('Mango Alley', ARRAY['Progressive House'], 'demo@themangoalley.com', 'https://soundcloud.com/themangoalley', true),
('Jee Productions', ARRAY['Progressive House'], 'demos@jee-productions.com', 'https://soundcloud.com/jeeproductions', true),
('Zerothree Music', ARRAY['Progressive House','Trance'], 'https://www.label-worx.com/demo/zerothree-demo-drop', 'https://soundcloud.com/zerothree-music', true),
('Afterglow Records', ARRAY['Progressive House'], 'info@afterglow-records.de', 'https://soundcloud.com/afterglowrecords', true),
('Atmosphere Records', ARRAY['Progressive House'], 'promo@atmosphere-records.com', 'https://soundcloud.com/atmosphererecords', true),
('New State Music', ARRAY['Progressive House','Bass House','Breaks'], 'https://www.newstatemusic.com/', 'https://soundcloud.com/newstatemusic', true),
('Bonzai Progressive', ARRAY['Progressive House','Trance'], 'https://soundcloud.com/marnikbonzai', 'https://soundcloud.com/marnikbonzai', true),
('Movement Recordings', ARRAY['Progressive House'], 'demos@movement-recordings.net', 'https://soundcloud.com/movement-recordings', true),
('OKO Recordings', ARRAY['Progressive House'], 'sebastian@betoko.com', 'https://soundcloud.com/okorecordings', true),
('Nothing Else Matters', ARRAY['Progressive House','Tech House'], 'music@nothingelsematters.co.uk', 'https://soundcloud.com/nothingelsemattersuk', true),
('Infectious Music', ARRAY['Progressive House'], 'demos.uk@bmg.com', 'https://soundcloud.com/infectiousmusicuk', true),
('Clubsonica Records', ARRAY['Progressive House'], 'demo@clubsonica.com', 'https://soundcloud.com/clubsonicarec', true),
('onedotsixtwo', ARRAY['Progressive House'], 'info@onedotsixtwo.com', 'https://soundcloud.com/onedotsixtwo', true),
('Nettwerk Music Group', ARRAY['Progressive House'], 'info@nettwerk.com', 'https://soundcloud.com/nettwerkmusicgroup', true),
('Black Hole Recordings', ARRAY['Progressive House','Trance','Psy-trance'], 'demos@blackholerecordings.com', 'https://soundcloud.com/blackholerecordings', true),
('Manual Music', ARRAY['Progressive House'], 'https://www.labelradar.com/labels/manualmusic/portal', 'https://soundcloud.com/manual-music', true),
('Or Two Strangers', ARRAY['Progressive House'], 'info.ortwostrangers@gmail.com', 'https://soundcloud.com/or-two-strangers', true),
('Eat My Hat Music', ARRAY['Progressive House'], 'demo@eatmyhatmusic.com', 'https://soundcloud.com/eatmyhat', true),
('Balkan Connection', ARRAY['Progressive House'], 'balkan.connection.records@gmail.com', 'https://soundcloud.com/balkan-connection', true),
('Soundteller Records', ARRAY['Progressive House'], 'info@soundtellerrecords.com', 'https://soundcloud.com/soundteller-records', true),
('Area Verde', ARRAY['Progressive House'], 'demo@area-verde.com', 'https://soundcloud.com/areaverde', true),
('Capital Heaven', ARRAY['Progressive House'], 'demo@capitalheaven.co.uk.', 'https://soundcloud.com/capital-heaven', true),
('Siona Records', ARRAY['Progressive House'], 'http://sionarecords.com/demo/', 'https://soundcloud.com/sionarecords', true),
('Silk Music', ARRAY['Progressive House'], 'www.silk-music.com/demos', 'https://soundcloud.com/silkmusic', true),
('Colorize (Enhanced Music)', ARRAY['Progressive House'], 'Send your demos and get in touch at www.colorizemusic.com', 'https://soundcloud.com/colorize-enhanced', true),
('Elliptical Sun Melodies', ARRAY['Progressive House'], 'demos@ellipticalsunmelodies.com', 'https://soundcloud.com/ellipticalsunmelodies', true),
('JOOF Recordings', ARRAY['Progressive House'], 'daniel@joof.co.uk', 'https://soundcloud.com/joof-recordings', true),
('Sound Avenue', ARRAY['Progressive House'], 'demo@soundavenue.be', 'https://soundcloud.com/soundavenue', true),
('Platipus', ARRAY['Progressive House'], 'platipus@platipus.com', 'https://soundcloud.com/platipusmusic', true),
('Full Tilt Recordings', ARRAY['Progressive House'], 'demos@fulltiltrecordings.ie', 'https://soundcloud.com/fulltiltrecordings', true),
('Yin : Yang', ARRAY['Progressive House'], 'tripp@protonradio.com', 'https://soundcloud.com/yin_yangmusic', true),
('Droid9', ARRAY['Progressive House'], 'droid9.demo@gmail.com', 'https://soundcloud.com/droid9recordings', true),
('MIR MUSIC', ARRAY['Progressive House'], 'demomirmusic@gmail.com', 'https://soundcloud.com/mirmusic_official', true),
('Univack Records', ARRAY['Progressive House'], 'contact@univack.com', 'https://soundcloud.com/univackrecords', true),
('Lauter Unfug Musik', ARRAY['Progressive House'], 'demos@lauter-unfug.com', 'https://soundcloud.com/lauter-unfug', true),
('EIN2', ARRAY['Progressive House'], 'demo@ein2.de', 'https://soundcloud.com/ein2', true),
('HIGHER STATES', ARRAY['Progressive House'], 'higherstatesrecordings@gmail.com', 'https://soundcloud.com/higherstatesmusic', true),
('Enchant Audio', ARRAY['Progressive House'], 'demos@enchantaudio.de', 'https://soundcloud.com/enchantaudio', true),
('Lowbit Records', ARRAY['Progressive House'], 'lowbitrecords.com', 'https://soundcloud.com/lowbit-records', true),
('ELEMENTS Series', ARRAY['Progressive House','Afro House'], 'thisiselements@gmail.com', 'https://soundcloud.com/elementsseries', true),
('Superordinate Music', ARRAY['Progressive House'], 'info@superordinatemusic.com', 'https://soundcloud.com/superordinate-music', true),
('No Art', ARRAY['Minimal|Deep Tech'], 'demos@noartmusic.com', 'https://soundcloud.com/noartmusic', true),
('Moan Recordings', ARRAY['Minimal|Deep Tech'], 'demo4moan@live.com', 'https://soundcloud.com/moanrecordings', true),
('hedZup records', ARRAY['Minimal|Deep Tech'], 'hedzuprecords@gmail.com', 'https://soundcloud.com/hedzup', true),
('Ole Records', ARRAY['Minimal|Deep Tech'], 'olerecordslabel@gmail.com', 'https://soundcloud.com/olerecords', true),
('e1even records', ARRAY['Minimal|Deep Tech'], 'Currently not accepting demos / Contact: e1evenrecords@hotmail.com', 'https://soundcloud.com/e1even-records', true),
('PIV', ARRAY['Minimal|Deep Tech'], 'chris@pivrecords.com / chris@pivrecords.com', 'https://soundcloud.com/pivrecords', true),
('Cyclic Records', ARRAY['Minimal|Deep Tech'], 'mihai@cyclic.ro', 'https://soundcloud.com/cyclicrecords', true),
('Dark Face Recordings', ARRAY['Minimal|Deep Tech'], 'demo.darkfacerecordings@gmail.com', 'https://soundcloud.com/darkfacerecordings', true),
('Bamboleo Records', ARRAY['Minimal|Deep Tech'], 'demos@bamboleorecords.com', 'https://soundcloud.com/bamboleorecords', true),
('Rendr Records', ARRAY['Minimal|Deep Tech'], 'demos@rendrrecords.co.uk', 'https://soundcloud.com/rendrrecords', true),
('Distance Music', ARRAY['Minimal|Deep Tech'], 'demos.distancemusic@gmail.com', 'https://soundcloud.com/distancemusicrecords', true),
('SIKR', ARRAY['Minimal|Deep Tech'], 'info@wearesikr.com', 'https://soundcloud.com/wearesikr', true),
('Whoyostro', ARRAY['Minimal|Deep Tech'], 'whoyostromusic@gmail.com', 'https://soundcloud.com/whoyostro', true),
('New Violence Records', ARRAY['Minimal|Deep Tech'], 'nvrdemos@gmail.com', 'https://soundcloud.com/newviolencerecords', true),
('PHOBIA Music Recordings', ARRAY['Minimal|Deep Tech'], 'phobiamusicrecordings@gmail.com', 'https://soundcloud.com/phobiamusicrecordings', true),
('SK Recordings', ARRAY['Minimal|Deep Tech'], 'demo@skrecordings.com', 'https://soundcloud.com/sk-recordings', true),
('Play Groove Recordings', ARRAY['Minimal|Deep Tech'], 'playgrooverecordings@hotmail.es', 'https://soundcloud.com/playgrooverecor', true),
('LIBERO', ARRAY['Minimal|Deep Tech'], 'demos@liberorecords.co.uk', 'https://soundcloud.com/libero_records', true),
('Psicodelica', ARRAY['Minimal|Deep Tech'], 'psicodelicalabel@gmail.com', 'https://soundcloud.com/psicodelicalabel', true),
('Little Helpers', ARRAY['Minimal|Deep Tech'], 'littlehelpers00@gmail.com', 'https://soundcloud.com/little-helpers', true),
('Nopreset Records', ARRAY['Minimal|Deep Tech'], 'demosnopresetrecords@gmail.com', 'https://soundcloud.com/nopresetrecordslabel', true),
('Black Sea Side Music', ARRAY['Minimal|Deep Tech'], 'blackseaside.manager@gmail.com', 'https://soundcloud.com/black-sea-side', true),
('Tamango Records', ARRAY['Minimal|Deep Tech'], 'promo@yayamusic.net', 'https://soundcloud.com/tamangorecords', true),
('Madtech Records', ARRAY['Minimal|Deep Tech'], 'demos@madtechrecords.co.uk', 'https://soundcloud.com/madtechrecords', true),
('NoExcuse', ARRAY['Minimal|Deep Tech'], 'demos@noexcuserecords.com', 'https://soundcloud.com/noexcuserecords', true),
('Hossh Records', ARRAY['Minimal|Deep Tech'], 'demo@hosshrecords.com', 'https://soundcloud.com/hosshrecords', true),
('Reshape Black', ARRAY['Minimal|Deep Tech'], 'reshapeblackdemo@gmail.com', 'https://soundcloud.com/reshapeblack', true),
('Hottrax', ARRAY['Minimal|Deep Tech','Tech House'], 'https://soundcloud.com/allhcdemos', 'https://soundcloud.com/hottraxmusic', true),
('Be One Records', ARRAY['Minimal|Deep Tech','Tech House'], 'demos@beonerecords.com', 'https://soundcloud.com/beonerecords', true),
('Unnamed & Unknown', ARRAY['Minimal|Deep Tech'], 'unnamed.unknown.demos@gmail.com', 'https://soundcloud.com/unnamed-unknown-2016', true),
('Innocent Music', ARRAY['Minimal|Deep Tech'], 'demos@innocentmusic.si', 'https://soundcloud.com/innocentmusic', true),
('PERCOMANIACS', ARRAY['Minimal|Deep Tech'], 'demos@percomaniacs.com', 'https://soundcloud.com/percomaniacs', true),
('MÜSE', ARRAY['Minimal|Deep Tech','Tech House'], 'demos@musicisthemuse.com', 'https://soundcloud.com/muse_records', true),
('RSH Promo Music Service', ARRAY['Minimal|Deep Tech'], 'http://www.roushlabel.com/?fbclid=IwAR0MtCtfKxYNDr5ypISkrmFMXLVJ1bMz9xvC4vrRze96mnARf4yHINpVGdU#/demos/', 'https://soundcloud.com/rshpromomusic', true),
('Resonance Records', ARRAY['Minimal|Deep Tech','Tech House'], 'aj@resonancerecords.co.uk', 'https://soundcloud.com/resonancerecords', true),
('Panterre Musique', ARRAY['Minimal|Deep Tech','Techno'], 'contact@stephenmacias.com', 'https://soundcloud.com/panterremusique', true),
('Downhill Music', ARRAY['Minimal|Deep Tech'], 'downhillmusic14@gmail.com', 'https://soundcloud.com/downhill-music', true),
('Sibil·la Music', ARRAY['Minimal|Deep Tech'], 'demos.sibil.lamusic@gmail.com', 'https://soundcloud.com/sibilamusic', true),
('BLA BLA', ARRAY['Minimal|Deep Tech'], 'http://www.blablamusic.com/index.php/home/contact/', 'https://soundcloud.com/blabla-music', true),
('DENSE AUDIO', ARRAY['Minimal|Deep Tech'], 'demo@dense-audio.net', 'https://soundcloud.com/denseaudio', true),
('Kaleydo Records', ARRAY['Minimal|Deep Tech'], 'demo@kaleydorecords.com', 'https://soundcloud.com/kaleydorecords', true),
('Syncopate Afterhours', ARRAY['Minimal|Deep Tech'], 'rlabel@syncopate.org', 'https://soundcloud.com/syncopateafterhours', true),
('Hatching Creatures', ARRAY['Minimal|Deep Tech'], 'Demos@Hatchingcreatures.com', 'https://soundcloud.com/hatching-creatures', true),
('Kenja Records', ARRAY['Minimal|Deep Tech'], 'kenjarecords@gmail.com', 'https://soundcloud.com/kenjarecords', true),
('R & S Records', ARRAY['Minimal|Deep Tech','Breaks'], 'verity@cookingvinyl.com', 'https://soundcloud.com/r-srecords', true),
('Under No Illusion', ARRAY['Minimal|Deep Tech','Tech House'], 'ki@undernoillusionrecordings.com', 'https://soundcloud.com/undernoillusionrecordings', true),
('Constant Sound', ARRAY['Minimal|Deep Tech'], 'Demos - SC Links to SC page Only. Thanks
https://soundcloud.com/constantsound', NULL, true),
('Fantastic Friends Rec.', ARRAY['Minimal|Deep Tech'], 'demo@fantasticfriends.ch', 'https://soundcloud.com/fantasticfriends', true),
('Desolat Music Group', ARRAY['Minimal|Deep Tech','Tech House'], 'http://desolat.com/?page_id=2092', 'https://soundcloud.com/desolat-music-group', true),
('Monocord', ARRAY['Minimal|Deep Tech'], 'monocordagency@gmail.com', 'https://soundcloud.com/monocordrecords', true),
('Distortion', ARRAY['Minimal|Deep Tech'], 'demos.distortion@gmail.com', 'https://soundcloud.com/distortion-label', true),
('Wow! Recordings', ARRAY['Minimal|Deep Tech'], 'demos@wow-recordings.com', 'https://soundcloud.com/wow-recordings', true),
('KinaMusic', ARRAY['Minimal|Deep Tech'], 'kinamusicofficial@gmail.com', 'https://soundcloud.com/kinamusic', true),
('Sola Records', ARRAY['Tech House'], 'music@solardo.net', 'https://soundcloud.com/solamusicuk', true),
('Sweat It Out', ARRAY['Tech House','Bass House'], 'https://sweatitoutmusic.com/contact/', 'https://soundcloud.com/sweat-it-out-music', true),
('La Pera Records', ARRAY['Tech House'], 'demoslapera@hotmail.com', 'https://soundcloud.com/laperarecords', true),
('Stashed Music', ARRAY['Tech House'], 'demos@stashedmusic.com', 'https://soundcloud.com/stashedmusic', true),
('savedrecords', ARRAY['Tech House','Afro House'], 'saveddemos@gmail.com', 'https://soundcloud.com/savedrecords', true),
('our_etiquette', ARRAY['Tech House'], 'Demos@ouretiquette.com', 'https://soundcloud.com/our_etiquette', true),
('Country Club Disco', ARRAY['Tech House'], 'https://biglink.to/CountryClubDisco', 'https://soundcloud.com/country-club-disco', true),
('Toolroom Trax', ARRAY['Tech House','Techno'], 'https://toolroomrecords.com/demos/', 'https://soundcloud.com/toolroom-trax', true),
('Wired', ARRAY['Tech House','Afro House'], 'demo@wiredmusic.eu', 'https://soundcloud.com/wiredonline', true),
('CIRCATRAX', ARRAY['Tech House'], 'https://circa18.com.au/contact', 'https://soundcloud.com/circatrax', true),
('LOW CEILING', ARRAY['Tech House'], 'https://lowceiling.com/contact', 'https://soundcloud.com/lowceiling', true),
('Rawsome Recordings', ARRAY['Tech House'], 'info@rawsomerecordings.com', 'https://soundcloud.com/rawsomerecords', true),
('Baikonur Recordings', ARRAY['Tech House'], 'demo@baikonurrecordings.com', 'https://soundcloud.com/baikonurrecordings', true),
('Flashmob Dj', ARRAY['Tech House','Afro House'], 'https://www.flashmobrecords.com/demos/', 'https://soundcloud.com/flashmob-dj', true),
('Basement Leak', ARRAY['Tech House'], 'music@basementleak.fr', 'https://soundcloud.com/basementleak', true),
('NONSTOP', ARRAY['Tech House'], 'demos@nonstoprec.com', 'https://soundcloud.com/nonstoprec', true),
('South Of Saturn', ARRAY['Tech House'], 'demos@repopulatemars.com', 'https://soundcloud.com/southofsaturn', true),
('Farris Wheel Recordings', ARRAY['Tech House'], 'farriswheelpromo@gmail.com', 'https://soundcloud.com/farris-wheel-recordings', true),
('Box Of Cats', ARRAY['Tech House','Bass House'], 'bocdemos@boxofcatsmusic.com', 'https://soundcloud.com/boxofcatsmusic', true),
('Rawthentic Music', ARRAY['Tech House'], 'rawthenticdemos@gmail.com', 'https://soundcloud.com/rawthenticmusic', true),
('Strangelove', ARRAY['Tech House','Breaks'], 'strangelove606@gmail.com', 'https://soundcloud.com/strangeloverecordings', true),
('Material Series', ARRAY['Tech House'], 'alvaro@materialseries.com', 'https://soundcloud.com/materialseries', true),
('Lost Records', ARRAY['Tech House'], 'demos@lostrecords.co.uk', 'https://soundcloud.com/lost-records', true),
('ABODE RECORDS', ARRAY['Tech House'], 'https://aboderecords.com/contact/', 'https://soundcloud.com/aboderecords', true),
('Safe Music Records', ARRAY['Tech House','Afro House'], 'safelabel@gmail.com', 'https://soundcloud.com/safelabel', true),
('Paul''s Boutique Music', ARRAY['Tech House'], 'paulsboutique.records@gmail.com', 'https://soundcloud.com/paulsboutiquemusic', true),
('Freakin Music', ARRAY['Tech House'], 'Freakindemo@gmx.co.uk', 'https://soundcloud.com/freakin909', true),
('Trippy Ass Technologies', ARRAY['Tech House','Breaks'], 'http://www.trippyasstechno.com/contact/', 'https://soundcloud.com/trippyasstechno', true),
('Terminal M Records', ARRAY['Techno'], 'rainer@terminalm.com', 'https://soundcloud.com/terminalm', true),
('Kraftek Music', ARRAY['Techno'], 'contact@kraftekmusic.com', 'https://soundcloud.com/a-kraftek-joint', true),
('Fe Chrome', ARRAY['Techno'], 'fechrome@t-online.de', 'https://soundcloud.com/fechromeofficial', true),
('Second State', ARRAY['Techno'], 'demo@secondstate.net', 'https://soundcloud.com/secondstateaudio', true),
('Codex Recordings', ARRAY['Techno'], 'demo@codexfamily.com', 'https://soundcloud.com/codexrecordings', true),
('Noir', ARRAY['Techno'], 'www.noir-music.com', 'https://soundcloud.com/noir', true),
('LEGEND', ARRAY['Techno'], 'demo@legend-audio.com', 'https://soundcloud.com/legendaudio', true),
('KD RAW', ARRAY['Techno'], 'techno@kd-raw.net', 'https://soundcloud.com/kd_raw_music', true),
('SENSO SOUNDS', ARRAY['Techno'], 'sounds@senso-sounds.net', 'https://soundcloud.com/senso-sounds', true),
('Respekt Recordings', ARRAY['Techno'], 'demos@respektrecordings.com', 'https://soundcloud.com/respektrecordings', true),
('JAM', ARRAY['Techno'], 'demo@wearejam.net', 'https://soundcloud.com/wearejam', true),
('Autektone Records', ARRAY['Techno'], 'demo@autektone.com', 'https://soundcloud.com/autektone', true),
('IAMT Label', ARRAY['Techno'], 'demo@spartaque.com', 'https://soundcloud.com/iamtlabel', true),
('Say What? Recordings', ARRAY['Techno'], 'djramontapia@hotmail.com', 'https://soundcloud.com/saywhatrecords', true),
('Orange Recordings', ARRAY['Techno'], 'demos@orange-recordings.com', 'https://soundcloud.com/orangerecordings', true),
('Silent Storm Rec.', ARRAY['Techno'], 'silentstormrec@gmail.com', 'https://soundcloud.com/silent-storm-rec', true),
('Phobiq Recordings', ARRAY['Techno'], 'sc@infactmusic.com', 'https://soundcloud.com/phobiqrecordings', true),
('Nervous Inc.', ARRAY['Techno'], 'Andrew@nervousnyc.com', 'https://soundcloud.com/nervous-records', true),
('Boysnoize Records', ARRAY['Techno'], 'info@boysnoize.com', 'https://soundcloud.com/boysnoizerecords', true),
('Intec Digital', ARRAY['Techno'], 'info@intecdigital.com', 'https://soundcloud.com/intec-digital', true),
('100percentpurerecords', ARRAY['Techno'], 'labels@planetgong.nl', 'https://soundcloud.com/100percentpurerecords', true),
('Klockworks Official', ARRAY['Techno'], 'demo@klockworks.de', 'https://soundcloud.com/klockworksofficial', true),
('Riot Recordings', ARRAY['Techno'], 'demo.riotrecordings@gmail.com', 'https://soundcloud.com/riot-recordings', true),
('Soma Records', ARRAY['Techno'], 'https://www.somarecords.com/contact/', 'https://soundcloud.com/soma', true),
('Black Kat', ARRAY['Techno'], 'demo@blackkatmusic.com', 'https://soundcloud.com/black-kat-7', true),
('BEK Audio', ARRAY['Techno'], 'info@bekaudio.com', 'https://soundcloud.com/bek-audio', true),
('Fierce Animals', ARRAY['Techno'], 'info@fierceanimals.com', 'https://soundcloud.com/fierceanimals', true),
('unri''li:s', ARRAY['Techno'], 'demo@rilisrec.com', 'https://soundcloud.com/rilis-records', true),
('Phantasy', ARRAY['Techno'], 'demos@phantasysound.co.uk', 'https://soundcloud.com/phantasysound', true),
('Involve Records', ARRAY['Techno'], 'demos@involverecords.es', 'https://soundcloud.com/involve-records', true),
('KISM', ARRAY['Techno'], 'info@kismrecordings.com', 'https://soundcloud.com/kismrecordings', true),
('trip', ARRAY['Techno'], 'promokraviz@gmail.com', 'https://soundcloud.com/triprecordings', true),
('OFF Recordings', ARRAY['Techno'], 'demos2019@off-recordings.com', 'https://soundcloud.com/off-recordings', true),
('Carti Records', ARRAY['Techno'], 'info@martin-books.com', 'https://soundcloud.com/carti-records', true),
('CUFF', ARRAY['Techno'], 'music@amineedge.com', 'https://soundcloud.com/thisiscuff', true),
('Future Sound of Egypt', ARRAY['Trance'], 'demos@futuresoundofegypt.com', 'https://soundcloud.com/fsoe-recordings', true),
('Garuda Music', ARRAY['Trance','Psy-trance','Hard Dance|Hardcore'], 'demo@garuda.nu', 'https://soundcloud.com/garuda_music', true),
('Afterdark', ARRAY['Trance'], 'afterdarkdemos@gmail.com', 'https://soundcloud.com/afterdark-rec', true),
('Amsterdam Trance (RazNitzanMusic)', ARRAY['Trance'], 'demo@raznitzanmusic.com', 'https://soundcloud.com/raznitzan', true),
('Coldharbour Recordings', ARRAY['Trance'], 'https://soundcloud.com/messages/102061578:62979659', 'https://soundcloud.com/coldharbourrecordings', true),
('Damaged Records', ARRAY['Trance'], 'promos@damaged-records.com', 'https://soundcloud.com/user-257141072', true),
('FSOE FABLES', ARRAY['Trance'], 'fables@futuresoundofegypt.com', 'https://soundcloud.com/fsoe-recordings', true),
('Kearnage Recordings', ARRAY['Trance'], 'kearnagerecordings@gmail.com', 'https://soundcloud.com/kearnagerecordings', true);

INSERT INTO labels (name, subgenres, email, soundcloud_url, accepts_demos) VALUES
('VANDITRecords', ARRAY['Trance'], 'demos@vandit.com', 'https://soundcloud.com/vanditrecords', true),
('Pure Trance', ARRAY['Trance'], 'demos@solarstone.co.uk', NULL, true),
('Flashover Recordings', ARRAY['Trance'], 'demo@flashoverrecordings.com', 'https://soundcloud.com/flashoverrecordings', true),
('Wake Your Mind Records', ARRAY['Trance'], 'WYM@cosmic-gate.de', 'https://soundcloud.com/cosmicgateofficial', true),
('AVA Recordings', ARRAY['Trance'], 'demos@avarecordings.com', 'https://soundcloud.com/avarecordings', true),
('Uplift Recordings (RazNitzanMusic)', ARRAY['Trance'], 'demos@upliftrecordings.com', NULL, true),
('Deep In Thought', ARRAY['Trance'], 'demos@amdeepinthought.com', 'https://soundcloud.com/amdeepinthought', true),
('Mental Asylum Records', ARRAY['Trance'], 'mentalasylumrecords@hotmail.com', 'https://soundcloud.com/mentalasylumrecords', true),
('Suanda Music', ARRAY['Trance'], 'demo@suandamusic.com', 'https://soundcloud.com/suandamusic', true),
('Always Alive Recordings', ARRAY['Trance'], 'https://www.label-worx.com/demo/enhanced?fbclid=IwAR3tra32F2By9s17vNrXt2FwF4jdKb8ibdUAjqAv_AwoIcLu8n8Ct_hgxhg', 'https://soundcloud.com/alwaysaliverecordings', true),
('Enhanced Progressive', ARRAY['Trance'], 'demos@enhancedmusic.com', 'https://soundcloud.com/enhancedprogressive', true),
('In Trance We Trust', ARRAY['Trance'], 'demos@intrancewetrust.com', NULL, true),
('Aria Digital Recordings', ARRAY['Trance'], 'ariadigitaldemos@gmail.com', 'https://soundcloud.com/ariadigital', true),
('Ride Recordings', ARRAY['Trance'], 'demo@riderecordings.com', 'https://soundcloud.com/ride-recordings', true),
('Digital Society Recs', ARRAY['Trance'], 'https://www.labelradar.com/labels/enhancedmusic/portal', 'https://soundcloud.com/digitalsocietyrecs', true),
('Otographic Music', ARRAY['Trance'], 'kenjisekiguchi@gmail.com', 'https://soundcloud.com/otographicmusic', true),
('In Charge (Be Yourself Music)', ARRAY['Trance'], 'https://beyourselfmusic.com/legacy/demos/', 'https://soundcloud.com/beyourselfmusic', true),
('Perfecto Records', ARRAY['Trance','Psy-trance'], 'demos@perfectorecords.com', 'https://soundcloud.com/perfectorecordings', true),
('Phoenix Recordings', ARRAY['Trance'], 'tracks@phoenix-recordings.net', 'https://soundcloud.com/phoenixrecordings', true),
('Reloaded Music', ARRAY['Trance'], 'demo@richarddurand.com', 'https://soundcloud.com/terminal_4', true),
('Serendipity Muzik', ARRAY['Trance'], 'onno@serendipitymuzik.com', 'https://soundcloud.com/serendipitymuzik', true),
('UV', ARRAY['Trance'], 'uv@futuresoundofegypt.com', 'https://soundcloud.com/fsoeuv', true),
('FSOE Parallels', ARRAY['Trance'], 'demos@futuresoundofegypt.com', 'https://soundcloud.com/fsoeparallels', true),
('Projekted Records', ARRAY['Trance'], 'projektedrecords@outlook.com', 'https://soundcloud.com/user-822384564', true),
('High Contrast Recordings', ARRAY['Trance'], 'https://beyourselfmusic.com/legacy/demos/', 'https://soundcloud.com/highcontrastrecordings', true),
('Trancegression Recordings', ARRAY['Trance'], 'demo@trancegression.com', 'https://soundcloud.com/user-331212115', true),
('Universal Nation', ARRAY['Trance'], 'demo@universalnation-official.com', 'https://soundcloud.com/alexmorph', true),
('Beyond The Stars Recordings', ARRAY['Trance'], 'beyondthestars@zoho.com', 'https://soundcloud.com/beyondthestarsrecordings', true),
('Intonenation Records', ARRAY['Trance'], 'demo@intonenationrecords.com', 'https://soundcloud.com/intonenationrecords', true),
('Elliptical Sun Recordings', ARRAY['Trance'], 'demos@ellipticalsunrecordings.com', 'https://soundcloud.com/elliptical-sun-recordings', true),
('RazNitzanMusic (RNM)', ARRAY['Trance'], 'demo@RazNitzanMusic.com', 'https://soundcloud.com/raznitzan', true),
('Universal Flow Records', ARRAY['Trance'], 'https://universal-flow-records.com/contact/demo-submission/', 'https://soundcloud.com/universal-flow-records', true),
('Extrema Global Music', ARRAY['Trance'], 'demo@extremaglobalmusic.com', 'https://soundcloud.com/extrema-global-music', true),
('Transistic Records', ARRAY['Trance'], 'demos@transistic.com', 'https://soundcloud.com/transisticrecords', true),
('Mondo Records', ARRAY['Trance'], 'https://www.mondorecords.com/submit-demo/', 'https://soundcloud.com/mondorecords', true),
('Tranceffect Records', ARRAY['Trance'], 'demo@tranceffectrecords.com', 'https://soundcloud.com/tranceffectrecords', true),
('Magic Island', ARRAY['Trance'], 'demo@rogershah.net', NULL, true),
('MoBlack', ARRAY['Trance','Afro House'], 'demo@moblack.com', 'https://soundcloud.com/moblack-records', true),
('Madorasindahouse', ARRAY['Afro House'], 'demo@madorasindahouse.com', 'https://soundcloud.com/madorasindahouse', true),
('Go Deeva Records', ARRAY['Afro House'], 'demo@godeeva.com', 'https://soundcloud.com/godeevarecords', true),
('Monaberry', ARRAY['Afro House'], 'demos@monaberry.de', 'https://soundcloud.com/monaberry', true),
('Seres Produções', ARRAY['Afro House'], 'info@seresproducoes.com', 'https://soundcloud.com/seres_producoes', true),
('Mule Musiq', ARRAY['Afro House'], 'info@mulemusiq.com', 'https://soundcloud.com/mulemusiq', true),
('PERPLEX! MUSIC', ARRAY['Afro House'], 'perplex.music@icloud.com', 'https://soundcloud.com/perplex-label', true),
('Erase Records', ARRAY['Afro House'], 'https://soundcloud.com/eraserecords', 'https://soundcloud.com/eraserecords', true),
('Stripped Down Records', ARRAY['Afro House'], 'demo@strippeddown.net', 'https://soundcloud.com/strippeddown', true),
('Sudam Recordings', ARRAY['Afro House'], 'demos@sudamrecordings.com', 'https://soundcloud.com/sudam', true),
('Cacao Records', ARRAY['Afro House'], 'cacaoisdope@gmail.com', 'https://soundcloud.com/cacaoisdope', true),
('Frau Blau Music', ARRAY['Afro House'], 'Fraublaudemo@gmail.com', 'https://soundcloud.com/fraublaumusic', true),
('Audiometrica Records', ARRAY['Afro House'], 'demo@audiometrica.com', 'https://soundcloud.com/audiometrica', true),
('Blue Shadow Records', ARRAY['Afro House'], 'blueshadowdemo@gmail.com', 'https://soundcloud.com/blueshadowrec', true),
('Bosom', ARRAY['Afro House'], 'bosomrecords@gmail.com', 'https://soundcloud.com/bosom', true),
('Poesie Musik', ARRAY['Afro House'], 'patrick@poesiemusik.com', 'https://soundcloud.com/poesiemusik', true),
('Union Records', ARRAY['Afro House'], 'demo.unionrecords@gmail.com', 'https://soundcloud.com/user-7186229', true),
('trueColors', ARRAY['Afro House'], 'Music@TrueColorsLabel.com', 'https://soundcloud.com/truecolorslabel', true),
('Vida Records', ARRAY['Afro House'], 'vidarecordsmusic@gmail.com', 'https://soundcloud.com/vidarecords', true),
('NuLu Music', ARRAY['Afro House'], 'demo@nulumusic.com', 'https://soundcloud.com/nulu-431516024', true),
('Retrolounge Records', ARRAY['Afro House'], 'retroloungerecords@gmail.com', 'https://soundcloud.com/retroloungerecords', true),
('Sweet Musique', ARRAY['Afro House'], 'nino@sweet-musique.com', 'https://soundcloud.com/sweetmusique', true),
('Tropical HEAT', ARRAY['Afro House'], 'tropicalheatrecords@gmail.com', 'https://soundcloud.com/tropical-heat-1', true),
('insomniacrecs', ARRAY['Bass House'], 'https://www.insomniacmusicgroup.com/label/insomniac-records/', 'https://soundcloud.com/insomniacrecords', true),
('Sink or Swim', ARRAY['Bass House'], 'frank@sinkorswim.biz', 'https://soundcloud.com/sinkorswimrecord', true),
('Premiere Classe', ARRAY['Bass House'], 'demos@premiereclasserecords.com', NULL, true),
('GOLD DIGGER', ARRAY['Bass House'], 'golddiggerrecs@gmail.com', 'https://soundcloud.com/golddiggerrecs', true),
('Lobster Boy Records', ARRAY['Bass House'], 'lobsterboydemos@gmail.com', 'https://soundcloud.com/lobsterboyrecords', true),
('[ MIX FEED ]', ARRAY['Bass House'], 'demos@mixfeedagency.com', 'https://soundcloud.com/mixfeedru', true),
('blackartel records', ARRAY['Bass House'], 'demos@blackartelrec.com', 'https://soundcloud.com/blackartelrec', true),
('Holy Molé!', ARRAY['Bass House'], 'https://www.holymolemusic.com/', 'https://soundcloud.com/holymolemusic', true),
('UP Club Records', ARRAY['Bass House'], 'demos@upclubrecords.org', 'https://soundcloud.com/upclubrecords', true),
('DUMB FAT RECORDS', ARRAY['Bass House'], 'dumbfatdemos@gmail.com', 'https://soundcloud.com/dumbfatrecords', true),
('SHEPPARD RECORDS', ARRAY['Bass House'], 'sheppardrecords@gmail.com', 'https://soundcloud.com/sheppard-records', true),
('Reactive Records', ARRAY['Bass House','Breaks'], 'oscar_22_32_32@hotmail.com', 'https://soundcloud.com/reactive-records', true),
('Formatik Records', ARRAY['Bass House'], 'demo@formatik-records.de', 'https://soundcloud.com/formatik-records', true),
('Audiophile XXL', ARRAY['Bass House','Breaks'], 'https://www.apmg.io/submit-demo/', 'https://soundcloud.com/audiophilexxl', true),
('Filthy Sounds', ARRAY['Bass House'], 'filthysounds2012@gmail.com', 'https://soundcloud.com/filthysounds', true),
('Juicy Music', ARRAY['Bass House'], 'demos@juicymusic.net', 'https://soundcloud.com/juicymusicofficial', true),
('RIM Label', ARRAY['Bass House'], 'info@iamtmusic.com', 'https://soundcloud.com/rimlabel', true),
('EPH''D UP RECORDS', ARRAY['Bass House'], 'ephduprecords@gmail.com', 'https://soundcloud.com/ephduprecords', true),
('Ravesta Records', ARRAY['Breaks'], 'https://ravesta.com/track-submission/', 'https://soundcloud.com/ravesta-records', true),
('Distorsion Records', ARRAY['Breaks'], 'distorsionrecords@hotmail.es', 'https://soundcloud.com/distorsionrecords', true),
('Elektroshok Records', ARRAY['Breaks'], 'elektroshokelectronicmusic@gmail.com', 'https://soundcloud.com/elektroshokrecords', true),
('GIGABEAT.us', ARRAY['Breaks'], 'info@gigabeat.us', 'https://soundcloud.com/gigabeatdotus', true),
('DIABLO LOCO', ARRAY['Breaks'], 'diablolocorecords@gmail.com', 'https://soundcloud.com/diablo-loco-records', true),
('SPACE PIZZA RECORDS', ARRAY['Breaks'], 'spacepizzarecords@gmail.com', 'https://soundcloud.com/spacepizzarecords', true),
('DogEatDog Records', ARRAY['Breaks'], 'dogeatdogrecs@gmail.com', 'https://soundcloud.com/dedr', true),
('illeven:eleven recordings', ARRAY['Breaks'], 'illeveneleven@gmail.com', 'https://soundcloud.com/illeven-eleven-recordings', true),
('Dizzines Records', ARRAY['Breaks'], 'www.dizzinesrecords.website/contact', 'https://soundcloud.com/dizzines-records', true),
('Hospital Records', ARRAY['Breaks','Drum&Bass'], 'www.hospitalrecords.com/demos/', 'https://soundcloud.com/hospitalrecords', true),
('Stars & Knights Records', ARRAY['Breaks'], 'starsknightrec@gmail.com', 'https://soundcloud.com/stars-knight-rec', true),
('Beat By Brain', ARRAY['Breaks'], 'info@spektra.es', 'https://soundcloud.com/beat-by-brain', true),
('DIESEL RECORDINGS', ARRAY['Breaks'], 'dieselrecordingsuk@gmail.com', 'https://soundcloud.com/dieselrecordings', true),
('Bombstrikes', ARRAY['Breaks'], 'admin@bombstrikes.net', 'https://soundcloud.com/bombstrikes', true),
('IBWTmusic', ARRAY['Breaks'], 'ibwtmusicdemo@gmail.com', 'https://soundcloud.com/ibwtmusic', true),
('Mecanoplastica Records', ARRAY['Breaks'], 'mecanoplasticarecords@gmail.com', 'https://soundcloud.com/mecanoplasticarecords', true),
('klubkids', ARRAY['Breaks'], 'klubkidsmusic@gmail.com', 'https://soundcloud.com/klubkids', true),
('spektramusic', ARRAY['Breaks'], 'info@spektra.es', 'https://soundcloud.com/spektramusic', true),
('OTHER PEOPLE', ARRAY['Breaks'], 'x@other-people.net', 'https://soundcloud.com/otherpeoplerecords', true),
('Westwood Recordings', ARRAY['Breaks'], 'http://westwoodrecordings.label-engine.com/demos', 'https://soundcloud.com/westwoodrecordings', true),
('Fantomas Records', ARRAY['Breaks'], 'fantomasrecords@gmail.com', 'https://soundcloud.com/fantomas-records', true),
('Empire Of Music Records', ARRAY['Breaks'], 'empireofmusicrec@gmail.com', 'https://soundcloud.com/empireom', true),
('BASSROCK RECORDS', ARRAY['Breaks'], 'demos@bassrockrecords.co.uk', 'https://soundcloud.com/bassrock-records', true),
('Low Groove Records', ARRAY['Breaks'], 'lowgrooverecords@gmail.com', 'https://soundcloud.com/lowgrooverecords', true),
('Musication Records', ARRAY['Breaks'], 'musicationrecords@gmail.com', 'https://soundcloud.com/musication-records', true),
('Psycho Disco!', ARRAY['Breaks'], 'hunter@psychodisco.com', 'https://soundcloud.com/psychodiscorecs', true),
('Multiplayer Records', ARRAY['Breaks'], 'http://labelmultiplayerrecords1.label-engine.com/demos', 'https://soundcloud.com/multiplayerrecords', true),
('Of Leisure', ARRAY['Breaks'], 'flock@ofleisure.com.au', 'https://soundcloud.com/of-leisure', true),
('Crookwell', ARRAY['Breaks'], 'crookwellrecords@gmail.com', 'https://soundcloud.com/crookwell', true),
('Xclubsive Recordings', ARRAY['Breaks'], 'info@spektra.es', 'https://soundcloud.com/xclubsiverecordings', true),
('Scour Records', ARRAY['Breaks'], 'info@scourrecords.com', 'https://soundcloud.com/scourrecords', true),
('Let''s Go Recordings', ARRAY['Breaks'], 'martin@ratrecords.info', 'https://soundcloud.com/letsgorecordings', true),
('Booty Trax', ARRAY['Breaks'], 'info@bootytrax.com', 'https://soundcloud.com/bootytrax', true),
('Delicious Groove Records', ARRAY['Breaks'], 'deliciousgrooverecords@gmail.com', 'https://soundcloud.com/delicious-groove-records', true),
('Gruvstation Music', ARRAY['Breaks'], 'gruvstation@hotmail.com', 'https://soundcloud.com/gruvstation', true),
('Cheap Thrills Records', ARRAY['Breaks'], 'cheapthrillsdemos@yahoo.co.uk', 'https://soundcloud.com/cheap-thrills-records', true),
('Prison Entertainment', ARRAY['Dance'], 'info@prison-entertainment.com', 'https://soundcloud.com/prison-entertainment', true),
('Epic Amsterdam', ARRAY['Dance'], 'info.nl@sonymusic.com', 'https://soundcloud.com/epic-amsterdam', true),
('Big Top Amsterdam', ARRAY['Dance'], 'bob@bigtopamsterdam.com', 'https://soundcloud.com/bigtopamsterdam', true),
('Be Yourself Music', ARRAY['Dance'], 'https://beyourselfmusic.com/legacy/demos/', 'https://soundcloud.com/beyourselfmusic', true),
('Perfect Havoc', ARRAY['Dance'], 'Adam.Griffin@perfecthavoc.com', 'https://soundcloud.com/perfecthavocmusic', true),
('SÓ TRACK BOA', ARRAY['Dance'], 'http://sotrackboademos.label-engine.com/demos', 'https://soundcloud.com/sotrackboa', true),
('Scorpio Music', ARRAY['Dance'], 'licensing@scorpiomusic.fr', 'https://soundcloud.com/scorpio-music', true),
('Good Company', ARRAY['Dance'], 'info@goodcompany.co', 'https://soundcloud.com/ingdco', true),
('Controversia records', ARRAY['Dance'], 'demo@controversiarecords.com', NULL, true),
('Fool''s Gold Records', ARRAY['Dance'], 'info@foolsgoldrecs.com', 'https://soundcloud.com/foolsgoldrecs', true),
('HEAVYWEIGHT RECORDS', ARRAY['Dance'], 'demos@heavyweightrecords.com', 'https://soundcloud.com/heavyweightrecords', true),
('Critical Music', ARRAY['Drum&Bass'], 'https://criticalmusic.com/contact/', 'https://soundcloud.com/critical-music', true),
('Shogun Audio', ARRAY['Drum&Bass'], 'http://shogunaudio.label-engine.com/demos', 'https://soundcloud.com/shogunaudio', true),
('1985 | Music', ARRAY['Drum&Bass'], '1985demos@gmail.com', 'https://soundcloud.com/1985music1985', true),
('Born On Road', ARRAY['Drum&Bass'], 'bornonroad@gmail.com', 'https://soundcloud.com/born-on-road', true),
('Elevate Records', ARRAY['Drum&Bass'], 'http://elevaterecords.label-engine.com/demos', 'https://soundcloud.com/elevaterecordsuk', true),
('Flexout Audio', ARRAY['Drum&Bass'], 'https://soundcloud.com/flexoutaudio / tom@flexoutaudio.com', 'https://soundcloud.com/flexoutaudio', true),
('TechniqueRecordings', ARRAY['Drum&Bass'], 'https://proshare.audio/technique-recordings', 'https://soundcloud.com/techniquerecordings', true),
('Playaz', ARRAY['Drum&Bass'], 'demosubs@playaz.co.uk', 'https://soundcloud.com/playazrecordings', true),
('V RECORDINGS', ARRAY['Drum&Bass'], 'http://www.vrecordings.com/content/demos', 'https://soundcloud.com/vrecordings', true),
('VISION', ARRAY['Drum&Bass'], 'noisia.nl/demos', 'https://soundcloud.com/visionrecordings', true),
('Souped Up Records', ARRAY['Drum&Bass'], 'soupeduprecords@gmail.com', 'https://soundcloud.com/soupeduprecords', true),
('EATBRAIN', ARRAY['Drum&Bass'], 'mailstoeatbrain@gmail.com', 'https://soundcloud.com/eatbrain', true),
('Overview Music', ARRAY['Drum&Bass'], 'overviewuk@gmail.com', 'https://soundcloud.com/overviewuk', true),
('Viper Recordings', ARRAY['Drum&Bass'], 'demos@viperrecordings.co.uk', 'https://soundcloud.com/viperrecordings', true),
('CIA Records', ARRAY['Drum&Bass'], 'info@ciarecords.co.uk', 'https://soundcloud.com/ciarecords', true),
('Metalheadz', ARRAY['Drum&Bass'], 'info@metalheadz.co.uk', 'https://soundcloud.com/metalheadz', true),
('DnB Allstars', ARRAY['Drum&Bass'], 'dnballstars@hotmail.com', 'https://soundcloud.com/dnballstars', true),
('Blackout Music NL', ARRAY['Drum&Bass'], 'https://www.blackoutmusic.nl/BlackoutMusic.html?journal_blog_post_id=124', 'https://soundcloud.com/blackoutmusicnl', true),
('Dispatch Recs | Ant TC1', ARRAY['Drum&Bass'], 'demos@dispatchrecordings.com', 'https://soundcloud.com/anttc1', true),
('TITAN RECORDS', ARRAY['Drum&Bass'], 'info@titan-records.co.uk', 'https://soundcloud.com/titanrecords', true),
('Delta9 Recordings', ARRAY['Drum&Bass'], 'info@delta9recordings.com', 'https://soundcloud.com/delta9recordings', true),
('UKF', ARRAY['Drum&Bass'], 'hello@ukf.com', 'https://soundcloud.com/ukf', true),
('biological beats', ARRAY['Drum&Bass'], 'biologicalbeats@hotmail.co.uk', 'https://soundcloud.com/biological-beats', true),
('Symmetry-Recordings', ARRAY['Drum&Bass'], 'demos@symmetryrecordings.co.uk', 'https://soundcloud.com/symmetry-recordings', true),
('LOW DOWN DEEP RECORDINGS', ARRAY['Drum&Bass'], 'lowdowndeeprecs@gmail.com', 'https://soundcloud.com/lowdowndeeprecs', true),
('Vandal Records', ARRAY['Drum&Bass'], 'vandalrecordshq@gmail.com', 'https://soundcloud.com/vandal-records', true),
('Fokuz Recordings', ARRAY['Drum&Bass'], 'http://bit.ly/1IqIPMg', 'https://soundcloud.com/fokuzrecordings', true),
('Skankandbass', ARRAY['Drum&Bass'], 'https://sendmusic.com/Skankandbass', 'https://soundcloud.com/skankandbass', true),
('Soul Trader Records', ARRAY['Drum&Bass'], 'lancejamescalder@gmail.com', 'https://soundcloud.com/soul-trader-records', true),
('Informal.', ARRAY['Drum&Bass'], 'informalrecordings@gmail.com', 'https://soundcloud.com/informalrecordings', true),
('SGN:LTD', ARRAY['Drum&Bass'], 'http://shogunaudio.label-engine.com/demos', 'https://soundcloud.com/sgn-ltd', true),
('Bad Taste Recordings', ARRAY['Drum&Bass'], 'demos@badtasterecordings.com', 'https://soundcloud.com/bad-taste-recordings', true),
('Lifestyle Music', ARRAY['Drum&Bass'], 'http://www.lifestylemusic.co.uk/demos/', 'https://soundcloud.com/lifestylemusic', true),
('Spearhead Records', ARRAY['Drum&Bass'], 'http://spearheadrecords.bigcartel.com/demo-submissions', 'https://soundcloud.com/spearheadrecords', true),
('Get Hype Records', ARRAY['Drum&Bass'], 'demos@gethyperecords.co', 'https://soundcloud.com/gethyperecords', true),
('WAR ON SILENCE', ARRAY['Drum&Bass'], 'https://www.waronsilence.com/contact', 'https://soundcloud.com/waronsilence', true),
('Jungle Cakes', ARRAY['Drum&Bass'], 'ben@hotcakes.info', 'https://soundcloud.com/junglecakes', true),
('CRUCAST', ARRAY['Drum&Bass'], 'music@crucast.com', 'https://soundcloud.com/crucast', true),
('InnergroundMusic', ARRAY['Drum&Bass'], 'http://labelinnergroundrecords.label-engine.com/demos', 'https://soundcloud.com/innergroundmusic', true),
('CHRONIC RECORDS', ARRAY['Drum&Bass'], 'http://www.vrecordings.com/content/demos', 'https://soundcloud.com/chronicrecs', true),
('0101 MUSIC', ARRAY['Drum&Bass'], 'https://www.0101music.com/demo/', 'https://soundcloud.com/0101music', true),
('AudioPorn Records', ARRAY['Drum&Bass'], 'demos@audiopornrecords.com', 'https://soundcloud.com/audiopornrecords', true),
('Celsius Recordings', ARRAY['Drum&Bass'], 'http://bit.ly/1IqIPMg', 'https://soundcloud.com/celsiusrecordings', true),
('Utopia Music', ARRAY['Drum&Bass'], 'utopiamusicuk@gmail.com', 'https://soundcloud.com/utopia-music', true),
('Let It Roll Recordings', ARRAY['Drum&Bass'], 'demos@letitroll.cz', 'https://soundcloud.com/let-it-roll-recordings', true),
('HOOFBEATS MUSIC', ARRAY['Drum&Bass'], 'music@hoofbeats.cz.', 'https://soundcloud.com/hoofbeatsmusic', true),
('Soulvent Records', ARRAY['Drum&Bass'], 'http://soulventrecords.label-engine.com/demos', 'https://soundcloud.com/soulventrecords', true),
('DEM Recordings', ARRAY['Drum&Bass'], 'hello@demrecordings.com', 'https://soundcloud.com/dem_recordings', true),
('Blue Tunes Records', ARRAY['Psy-trance'], 'info@bluetunes-records.com', 'https://soundcloud.com/blue-tunes-records', true),
('Spin Twist Records', ARRAY['Psy-trance'], 'For  demos, please send a private SoundCloud link to our SoundCloud account.', 'https://soundcloud.com/spin_twist_records', true),
('Digital Om', ARRAY['Psy-trance'], 'info@digitalomproductions.in', 'https://soundcloud.com/starlab-sounds', true),
('IONO MUSIC', ARRAY['Psy-trance'], 'info@iono-music.com', 'https://soundcloud.com/iono-music', true),
('United Beats Records', ARRAY['Psy-trance'], 'https://www.unitedbeatsrecords.com/', 'https://soundcloud.com/unitedbeatsrecords', true),
('Dacru Records', ARRAY['Psy-trance'], 'demos@dacru.be', 'https://soundcloud.com/dacru', true),
('Expo Records', ARRAY['Psy-trance'], 'exporecords@bdproductions.co.za', 'https://soundcloud.com/exporecords', true),
('Maharetta Records', ARRAY['Psy-trance'], 'maharettarecords@gmail.com', 'https://soundcloud.com/maharetta-records', true),
('Alteza Records', ARRAY['Psy-trance'], 'demo@alteza-records.com', 'https://soundcloud.com/alteza-records', true),
('VII', ARRAY['Psy-trance'], 'info@theviicrew.com', 'https://soundcloud.com/theviicrew', true),
('TIP Records', ARRAY['Psy-trance'], 'http://www.tiprecords.com/contacttip/', 'https://soundcloud.com/tiprecords', true),
('Antu Records', ARRAY['Psy-trance'], 'contact@anturecords.com', 'https://soundcloud.com/itallive', true),
('X7M Records', ARRAY['Psy-trance'], 'x7mrecords@hotmail.com', 'https://soundcloud.com/x7m-records', true),
('Alien Records', ARRAY['Psy-trance'], 'https://alienrec.com/demos/', 'https://soundcloud.com/alienrec', true),
('Sonoora Records', ARRAY['Psy-trance'], 'http://www.sonoorarecords.com.br/#/demos', 'https://soundcloud.com/sonoorarecords', true),
('Avant Garde Music', ARRAY['Psy-trance'], 'avantgardemusicbr@gmail.com', 'https://soundcloud.com/avantgardemusicbr', true),
('Nocturnal Knights Music', ARRAY['Psy-trance'], 'demo@nocturnalknightsmusic.com', 'https://soundcloud.com/nocturnalknightsmusic', true),
('Sahman Records', ARRAY['Psy-trance'], 'sahman.records@gmail.com', 'https://soundcloud.com/sahmanrecords', true),
('Profound Records', ARRAY['Psy-trance'], 'music@profoundrecords.in', 'https://soundcloud.com/profoundrecords', true),
('BMSS Records', ARRAY['Psy-trance'], 'bmssrecords@gmail.com', 'https://soundcloud.com/bmss-records', true),
('Looney Moon Records', ARRAY['Psy-trance'], 'info@looney-moon.com', 'https://soundcloud.com/looney-moon-records', true),
('Transcape Records', ARRAY['Psy-trance'], 'transcape.records@gmail.com', 'https://soundcloud.com/transcape-records', true),
('BlackLite Records', ARRAY['Psy-trance'], 'info@blackliterecords.com', 'https://soundcloud.com/blackliterecords', true),
('SOLAR TECH RECORDS', ARRAY['Psy-trance'], 'info@solartechrecords.de', 'https://soundcloud.com/solartechrecords', true),
('astralwerks', ARRAY['Psy-trance'], 'astralwerks.astralwerks@gmail.com', 'https://soundcloud.com/astralwerks', true),
('Pharmacymusic', ARRAY['Psy-trance'], 'https://www.label-worx.com/demo/pharmacy-music', 'https://soundcloud.com/pharmacymusic', true),
('Teamwrk Records', ARRAY['Psy-trance','Hard Dance|Hardcore'], 'https://labelteamwrkrecords.label-engine.com/demos', 'https://soundcloud.com/teamwrkrecords', true),
('Musata Music', ARRAY['Psy-trance'], 'demo@musatamusic.com', 'https://soundcloud.com/musata_music', true),
('Sangoma Records', ARRAY['Psy-trance'], 'daksinamurti@hotmail.com gatafreak@sangomarecords.com', 'https://soundcloud.com/sangoma-recs', true),
('Cultura Psy Trance', ARRAY['Psy-trance'], 'contato.edu92@gmail.com', 'https://soundcloud.com/culturapsytrance', true),
('Critical Overload', ARRAY['Psy-trance'], 'david@komplexsounds.com', NULL, true),
('Let It Out Records', ARRAY['Psy-trance'], 'letitoutrecords@gmail.com', 'https://soundcloud.com/let-it-out-records', true),
('Mainstage Records', ARRAY['Psy-trance'], 'demo@mainstage-records.com', 'https://soundcloud.com/mainstagerecords', true),
('1 2 Trip Records', ARRAY['Psy-trance'], '12triprecords@gmail.com', 'https://soundcloud.com/12triprecords', true),
('Mosaico Records', ARRAY['Psy-trance'], 'info@mosaicorecords.com', 'https://soundcloud.com/mosaico-records', true),
('FxxK Tomorrow', ARRAY['Psy-trance'], 'demosfxxktomorrow@gmail.com', 'https://soundcloud.com/fxxktomorrow', true),
('Progg''N''Roll Records', ARRAY['Psy-trance'], 'progg.n.roll.records@gmail.com', 'https://soundcloud.com/progg_n_roll', true),
('SmileCreationsMusicLabel', ARRAY['Psy-trance'], 'info@smilecreations-music-label.com', 'https://soundcloud.com/smilecreationsmusiclabel', true),
('Rizoma Records', ARRAY['Psy-trance'], 'rizomarecords@gmail.com', 'https://soundcloud.com/rizoma-records', true),
('Enterrec', ARRAY['Psy-trance'], 'enterrecinfo@gmail.com', 'https://soundcloud.com/enterrec', true),
('Oryx Music', ARRAY['Psy-trance'], 'http://oryxmusic.net/send-demos/', 'https://soundcloud.com/oryxmusic', true),
('Roll-In Groove Records', ARRAY['Psy-trance'], 'info@roll-in-groove.co.uk', 'https://soundcloud.com/roll-in-groove-records', true),
('Ovnimoon Records', ARRAY['Psy-trance'], 'ovnimoon@gmail.com', 'https://soundcloud.com/ovnimoon-records', true),
('Dirty Workz', ARRAY['Hard Dance|Hardcore'], 'https://docs.google.com/forms/d/e/1FAIpQLSfse_OHjfFw9mXgzW9NAX2u8Rw0JTojFz4ULsU04FfqAJFbNw/viewform', 'https://soundcloud.com/dirtyworkzofficial', true),
('OneSeventy', ARRAY['Hard Dance|Hardcore'], 'oneseventy.au@gmail.com', 'https://soundcloud.com/oneseventy', true),
('Scantraxx', ARRAY['Hard Dance|Hardcore'], 'https://www.scantraxx.com/demos/', 'https://soundcloud.com/scantraxx', true),
('Art of Creation', ARRAY['Hard Dance|Hardcore'], 'https://artofcreation.com/demos/', 'https://soundcloud.com/artofcreationofficial', true),
('BTID Music', ARRAY['Hard Dance|Hardcore'], 'submissions@btidmusic.co.uk', 'https://soundcloud.com/musicbtid', true),
('Roughstate', ARRAY['Hard Dance|Hardcore'], 'info@roughstatemusic.com', 'https://soundcloud.com/roughstatemusic', true),
('Xploded Music', ARRAY['Hard Dance|Hardcore'], 'xplodedmusicdemos@gmail.com', 'https://soundcloud.com/xplodedmusic', true),
('24/7 Hardcore', ARRAY['Hard Dance|Hardcore'], 'altaylorpersonal@gmail.com', 'https://soundcloud.com/alstorm', true),
('Keeping The Rave Alive', ARRAY['Hard Dance|Hardcore'], 'info@keepingtheravealive.com', 'https://soundcloud.com/keepingtheravealive', true),
('End of Line', ARRAY['Hard Dance|Hardcore'], 'https://endofline.nl/?fbclid=IwAR3VgMvubVL_bbWXlZKmt9I9lV-_Kxq0KXyYRU7H1rvXVPdfJmAOfoRY3_A', 'https://soundcloud.com/endoflinerecordings', true),
('Justice Hardcore', ARRAY['Hard Dance|Hardcore'], 'info@justicehardcore.com', 'https://soundcloud.com/justicehardcore', true),
('Gearbox Euphoria', ARRAY['Hard Dance|Hardcore'], 'sjoerd@gearboxdigital.com', 'https://soundcloud.com/gearbox-digital', true),
('Barong Family', ARRAY['Hard Dance|Hardcore'], 'demos@barongfamily.com', 'https://soundcloud.com/barongfamily', true),
('I AM HARDSTYLE', ARRAY['Hard Dance|Hardcore'], 'info@iamhardstyle.com', 'https://soundcloud.com/iamhardstyle', true),
('DNZ Records', ARRAY['Hard Dance|Hardcore'], 'info@dnz-records-com', 'https://soundcloud.com/dnzrecords', true),
('Cheeky Tracks', ARRAY['Hard Dance|Hardcore'], 'generalbouncecheekytracks@live.co.uk', 'https://soundcloud.com/cheekytracks', true),
('WE R Music', ARRAY['Hard Dance|Hardcore'], 'http://www.wer-music.com/', 'https://soundcloud.com/wermusic', true),
('Contagious Records', ARRAY['Hard Dance|Hardcore'], 'contagousrecords@outlook.com', 'https://soundcloud.com/contagious-records', true),
('Fvck Genres', ARRAY['Hard Dance|Hardcore'], 'http://fvckgenres.com/demos/', 'https://soundcloud.com/fvckgenres', true),
('JAKD Recordings', ARRAY['Hard Dance|Hardcore'], 'https://docs.google.com/forms/d/e/1FAIpQLSfLbkWHqJXRF5KEnK9I3Sd3o2vud8WwCLG8pCGxZ5_gaRwFxw/viewform', 'https://soundcloud.com/jakdrecordings', true),
('We Are One Digital', ARRAY['Hard Dance|Hardcore'], 'https://weareone.digital/demodrop', 'https://soundcloud.com/weareonedigital', true),
('HDFK Records', ARRAY['Hard Dance|Hardcore'], 'https://labelhdfkrecords.label-engine.com/demos?fbclid=IwAR3mLaCm3_W2uAtdxvJtk5fd74s49CZmOGQO_qEIZUPPf1BPzZ6ARvd3GUM', 'https://soundcloud.com/hdfkrecords', true),
('Q-dance Records', ARRAY['Hard Dance|Hardcore'], 'tracks@q-dance.com', 'https://soundcloud.com/q-dancerecords', true),
('BASSCON', ARRAY['Hard Dance|Hardcore'], 'https://www.bassconmassive.com/contact-us/', 'https://soundcloud.com/basscon', true),
('Nightbreed', ARRAY['Hard Dance|Hardcore'], 'demos@wearethenightbreed.com', 'https://soundcloud.com/wearethenightbreed', true),
('HARSH RECORDS', ARRAY['Hard Dance|Hardcore'], 'https://www.harshrecords.com/pages/contact', 'https://soundcloud.com/harshrecordslabel', true),
('HPTG Music', ARRAY['Hard Dance|Hardcore'], 'info@hptgmusic.com', 'https://soundcloud.com/hptgmusic', true),
('Dogfight Records', ARRAY['Hard Dance|Hardcore'], 'demo@dogfightrec.com', 'https://soundcloud.com/dogfightrec', true),
('Derailed Traxx Records', ARRAY['Hard Dance|Hardcore'], 'https://beyourselfmusic.com/legacy/demos/', 'https://soundcloud.com/derailedtraxx', true),
('Koda Recordings', ARRAY['Hard Dance|Hardcore'], 'https://www.kodarecordings.co.uk/contact', 'https://soundcloud.com/kodarecordings', true),
('BONZAI CLASSICS', ARRAY['Hard Dance|Hardcore'], 'https://www.bonzaiclassics.com/demos/', NULL, true),
('Gud Vibrations', ARRAY['Hard Dance|Hardcore'], 'promo@gudvibrations.com', 'https://soundcloud.com/gudvibrations', true),
('Reaching Altitude', ARRAY['Hard Dance|Hardcore'], 'demos@reachingaltitude.com', 'https://soundcloud.com/reachingaltituderecords', true),
('Good Enuff', ARRAY['Hard Dance|Hardcore'], 'https://demos.disco.ac/upload/238206/demos/?signature=yiHKzWEZ6xHSERAtPulKJVjvNEs%3AqhCD9L7p', 'https://soundcloud.com/goodenuff', true),
('Dutch Master Works', ARRAY['Hard Dance|Hardcore'], 'dmw@2-dutch.com', 'https://soundcloud.com/dutchmasterworks', true),
('Foolish', ARRAY['Hard Dance|Hardcore'], 'demos@foolish.wtf', 'https://soundcloud.com/foolishwtf', true);

